// offlineDatabase.js — SehatGemma True Offline Engine
// 40+ Pakistani foods with pre-computed diabetic analysis
// Zero AI needed. 200KB. Works on $50 phone. Instant response.

const PAKISTANI_FOODS = [
  {
    name: 'biryani',
    aliases: ['biryani', 'biryan', 'baryani', 'biryani rice', 'chicken biryani', 'beef biryani', 'mutton biryani'],
    risk_level: 'high',
    glycemic_index: 70,
    food_name_en: 'Biryani',
    food_name_ur: 'بریانی',
    explanation_en: 'White rice has high GI (70). The oil and meat slow absorption slightly, but the large rice portion spikes glucose within 30-45 minutes. One plate ≈ 80-100g carbs. High risk for retinopathy and nephropathy.',
    explanation_ur: 'چاول کی وجہ سے شوگر تیزی سے بڑھتی ہے۔ ایک پیالے میں 80-100 گرام کاربوہائیڈریٹ ہوتے ہیں۔ 30-45 منٹ میں گلوکوز بڑھ جاتا ہے۔',
    swap_suggestion_en: 'Swap to cauliflower rice biryani (Gobi Biryani) or 50/50 brown basmati mix. Add raita to slow absorption.',
    swap_suggestion_ur: 'گوبھی والی بریانی یا براؤن باسمتی چاول استعمال کریں۔ رائتہ ساتھ کھائیں۔',
    portion_advice: 'Max 1 cup cooked. Eat with salad first.',
    carbs_g: 80,
    calories_estimate: '~450 kcal',
    category: 'rice'
  },
  {
    name: 'nihari',
    aliases: ['nihari', 'nihari gosht', 'beef nihari', 'mutton nihari'],
    risk_level: 'medium',
    glycemic_index: 15,
    food_name_en: 'Nihari',
    food_name_ur: 'نہاری',
    explanation_en: 'Low carb but extremely high fat. The flour (maida) thickener adds hidden carbs. Fat delays but does not prevent glucose rise. One bowl ≈ 30g carbs + high saturated fat.',
    explanation_ur: 'گوشت ٹھیک ہے مگر نان اور گندم کا آٹا نقصان دہ ہے۔ ایک پیالے میں 30 گرام کاربوہائیڈریٹ اور بہت زیادہ چکنائی ہے۔',
    swap_suggestion_en: 'Skip the naan. Use 1 small multigrain roti. Ask for less flour thickener.',
    swap_suggestion_ur: 'نان نہ کھائیں۔ ملٹی گرین روٹی استعمال کریں۔',
    portion_advice: '1 small bowl (300ml). Never with naan.',
    carbs_g: 30,
    calories_estimate: '~350 kcal',
    category: 'meat'
  },
  {
    name: 'haleem',
    aliases: ['haleem', 'beef haleem', 'chicken haleem', 'haleem recipe'],
    risk_level: 'high',
    glycemic_index: 65,
    food_name_en: 'Haleem',
    food_name_ur: 'حلیم',
    explanation_en: 'Wheat + lentils + meat. The wheat dominates. Blended texture means faster absorption. One bowl ≈ 60-70g carbs. High glycemic load.',
    explanation_ur: 'گندم اور دالیں مل کر شوگر بڑھاتی ہیں۔ ایک پیالے میں 60-70 گرام کاربوہائیڈریٹ ہے۔',
    swap_suggestion_en: 'Chicken haleem with 50% less wheat. Add extra ginger and lemon.',
    swap_suggestion_ur: 'چکن حلیم میں گندم آدھی کریں۔ ادرک اور لیموں ڈالیں۔',
    portion_advice: 'Half bowl only. Eat with cucumber salad.',
    carbs_g: 65,
    calories_estimate: '~380 kcal',
    category: 'lentils'
  },
  {
    name: 'saag with makai roti',
    aliases: ['saag', 'makai roti', 'corn roti', 'makki roti', 'sarson ka saag'],
    risk_level: 'low',
    glycemic_index: 45,
    food_name_en: 'Saag with Makai Roti',
    food_name_ur: 'ساگ اور مکئی کی روٹی',
    explanation_en: 'Makai (corn) roti has lower GI than wheat. Saag is fiber-rich and slows absorption. Best combination for diabetics. Rich in iron and magnesium.',
    explanation_ur: 'مکئی کی روٹی اور ساگ بہترین ہے۔ فائبر زیادہ ہے، شوگر آہستہ بڑھتی ہے۔',
    swap_suggestion_en: 'Already optimal. Just avoid adding too much butter/ghee.',
    swap_suggestion_ur: 'پہلے سے بہترین ہے۔ گھی کم ڈالیں۔',
    portion_advice: '2 small makai rotis max. Unlimited saag.',
    carbs_g: 30,
    calories_estimate: '~250 kcal',
    category: 'vegetables'
  },
  {
    name: 'chana chaat',
    aliases: ['chana chaat', 'chickpea chaat', 'cholay chaat', 'chana chat'],
    risk_level: 'low',
    glycemic_index: 35,
    food_name_en: 'Chana Chaat',
    food_name_ur: 'چنا چاٹ',
    explanation_en: 'Chickpeas are low GI, high fiber, high protein. The spices and lemon are anti-inflammatory. Excellent diabetic snack. One cup = 15g protein.',
    explanation_ur: 'چنے شوگر کے لیے بہترین ہیں۔ فائبر اور پروٹین زیادہ ہے۔ میٹھی چٹنی نہ ڈالیں۔',
    swap_suggestion_en: 'Already optimal. Avoid sweet tamarind chutney. Add yogurt for extra protein.',
    swap_suggestion_ur: 'پہلے سے بہترین ہے۔ میٹھی املی کی چٹنی نہ ڈالیں۔ دہی ڈال کر کھائیں۔',
    portion_advice: '1 cup is a full meal. Add yogurt for protein.',
    carbs_g: 27,
    calories_estimate: '~200 kcal',
    category: 'lentils'
  },
  {
    name: 'gulab jamun',
    aliases: ['gulab jamun', 'gulabjamun', 'sweet', 'mithai'],
    risk_level: 'high',
    glycemic_index: 95,
    food_name_en: 'Gulab Jamun',
    food_name_ur: 'گلاب جامن',
    explanation_en: 'Deep fried + sugar syrup. One piece = 25g sugar + 15g fat. Glucose spike within 15 minutes. Dangerous for diabetics. Increases retinopathy risk.',
    explanation_ur: 'یہ شوگر مریضوں کے لیے زہر ہے۔ ایک پیس میں 25 گرام چینی ہے۔ 15 منٹ میں شوگر بہت بڑھ جاتی ہے۔',
    swap_suggestion_en: 'Sugar-free ras malai (homemade with stevia) or dates (1-2 only).',
    swap_suggestion_ur: 'بغیر چینی کی رس ملائی یا 1-2 کھجور کھائیں۔',
    portion_advice: 'ZERO for diabetics. If unavoidable, 1 piece once a month.',
    carbs_g: 25,
    calories_estimate: '~175 kcal',
    category: 'dessert'
  },
  {
    name: 'siri paye',
    aliases: ['siri paye', 'paye', 'trotters', 'siri'],
    risk_level: 'medium',
    glycemic_index: 5,
    food_name_en: 'Siri Paye',
    food_name_ur: 'سری پائے',
    explanation_en: 'Almost zero carbs. Pure collagen and fat. Will not spike glucose but very high cholesterol. Not for heart patients. Good for joints.',
    explanation_ur: 'کاربوہائیڈریٹ نہیں مگر چربی بہت ہے۔ نان کے بغیر کھائیں۔ دل کے مریضوں کے لیے نہیں۔',
    swap_suggestion_en: 'Already low carb. Skip the naan, eat with 1 small roti.',
    swap_suggestion_ur: 'نان نہ کھائیں۔ ایک چھوٹی روٹی کے ساتھ کھائیں۔',
    portion_advice: '1 small bowl. Once a week max.',
    carbs_g: 5,
    calories_estimate: '~300 kcal',
    category: 'meat'
  },
  {
    name: 'fruit chaat',
    aliases: ['fruit chaat', 'fruit salad', 'fruit chat'],
    risk_level: 'medium',
    glycemic_index: 55,
    food_name_en: 'Fruit Chaat',
    food_name_ur: 'فروٹ چاٹ',
    explanation_en: 'Depends on fruits. Banana, mango, grapes = high. Apple, guava, papaya = low. Ramadan staple but watch portions. Masala helps slow absorption.',
    explanation_ur: 'امرود، سیب، پپیتا ٹھیک ہیں۔ کیلا اور آم سے پرہیز کریں۔ مسالا شوگر کم کرنے میں مدد دیتا ہے۔',
    swap_suggestion_en: 'Use only guava, apple, papaya, pomegranate. Avoid banana and mango.',
    swap_suggestion_ur: 'صرف امرود، سیب، پپیتا، انار استعمال کریں۔',
    portion_advice: '1 cup max. Best before exercise.',
    carbs_g: 25,
    calories_estimate: '~120 kcal',
    category: 'fruit'
  },
  {
    name: 'lassi',
    aliases: ['lassi', 'sweet lassi', 'salted lassi', 'meethi lassi'],
    risk_level: 'high',
    glycemic_index: 60,
    food_name_en: 'Lassi',
    food_name_ur: 'لسی',
    explanation_en: 'Sweet lassi = liquid sugar. 1 glass ≈ 30g sugar. Absorbs faster than solid food. Salted lassi is fine and provides probiotics.',
    explanation_ur: 'میٹھی لسی شوگر بڑھاتی ہے۔ ایک گلاس میں 30 گرام چینی ہے۔ نمکین لسی پیئیں۔',
    swap_suggestion_en: 'Salted lassi with roasted cumin. Or chaas (buttermilk).',
    swap_suggestion_ur: 'نمکین لسی یا چھاچھ پیئیں۔ بھنا زیرہ ڈالیں۔',
    portion_advice: 'Sweet: NEVER. Salted: 1 glass with meal.',
    carbs_g: 30,
    calories_estimate: '~180 kcal',
    category: 'drink'
  },
  {
    name: 'keema naan',
    aliases: ['keema naan', 'qeema naan', 'naan', 'keema'],
    risk_level: 'high',
    glycemic_index: 75,
    food_name_en: 'Keema Naan',
    food_name_ur: 'قیمہ نان',
    explanation_en: 'Maida naan + keema. Double danger: refined flour + meat fat. One naan ≈ 50g carbs. Very high GI. Causes rapid glucose spike.',
    explanation_ur: 'نان کا آٹا نقصان دہ ہے۔ ایک نان میں 50 گرام کاربوہائیڈریٹ ہے۔',
    swap_suggestion_en: 'Keema with 1 small whole wheat roti. Or lettuce wrap keema.',
    swap_suggestion_ur: 'قیمہ روٹی کے ساتھ کھائیں۔ نان سے پرہیز کریں۔',
    portion_advice: 'Half naan max. Better to avoid entirely.',
    carbs_g: 50,
    calories_estimate: '~400 kcal',
    category: 'bread'
  },
  {
    name: 'shami kebab',
    aliases: ['shami kebab', 'shami kabab', 'shami'],
    risk_level: 'low',
    glycemic_index: 20,
    food_name_en: 'Shami Kebab',
    food_name_ur: 'شامی کباب',
    explanation_en: 'Lentils + meat. Pan-fried, not deep fried. Good protein source. The chana dal adds slow carbs. Low glycemic impact.',
    explanation_ur: 'شامی کباب پروٹین کا اچھا ذریعہ ہے۔ چنے کی دال شوگر آہستہ بڑھاتی ہے۔',
    swap_suggestion_en: 'Already good. Grill instead of fry. Skip the chutney if sweet.',
    swap_suggestion_ur: 'پہلے سے اچھا ہے۔ تلنے کی بجائے گرل کریں۔',
    portion_advice: '2-3 pieces with salad. Good snack.',
    carbs_g: 10,
    calories_estimate: '~150 kcal',
    category: 'meat'
  },
  {
    name: 'dahi bhalla',
    aliases: ['dahi bhalla', 'dahi vada', 'dahi baray', 'dahi bara'],
    risk_level: 'high',
    glycemic_index: 70,
    food_name_en: 'Dahi Bhalla',
    food_name_ur: 'دہی بھلہ',
    explanation_en: 'Fried lentil dumplings in yogurt. The frying + sweet tamarind chutney makes it high risk. Yogurt helps slightly but not enough.',
    explanation_ur: 'تلا ہوا اور میٹھی چٹنی نقصان دہ ہے۔ دہی تھوڑی مدد کرتا ہے مگر کافی نہیں۔',
    swap_suggestion_en: 'Baked bhalla with salted yogurt. No sweet chutney.',
    swap_suggestion_ur: 'بیکڈ بھلے نمکین دہی کے ساتھ کھائیں۔ میٹھی چٹنی نہ ڈالیں۔',
    portion_advice: '2 pieces max if baked. Avoid fried.',
    carbs_g: 35,
    calories_estimate: '~250 kcal',
    category: 'snack'
  },
  {
    name: 'suji halwa',
    aliases: ['suji halwa', 'semolina halwa', 'halwa', 'sooji halwa'],
    risk_level: 'high',
    glycemic_index: 85,
    food_name_en: 'Suji Halwa',
    food_name_ur: 'سوجی کا حلوہ',
    explanation_en: 'Semolina + sugar + ghee. Triple threat. Very fast absorption. Common in breakfast, very dangerous for diabetics.',
    explanation_ur: 'حلوہ شوگر مریضوں کے لیے ممنوع ہے۔ سوجی، چینی، اور گھی تینوں نقصان دہ ہیں۔',
    swap_suggestion_en: 'Oatmeal with cinnamon and nuts. Or chia pudding.',
    swap_suggestion_ur: 'اوٹس دار چینی اور بادام کے ساتھ کھائیں۔',
    portion_advice: 'ZERO for diabetics.',
    carbs_g: 40,
    calories_estimate: '~300 kcal',
    category: 'dessert'
  },
  {
    name: 'chapli kebab',
    aliases: ['chapli kebab', 'chapli kabab', 'chapli'],
    risk_level: 'medium',
    glycemic_index: 25,
    food_name_en: 'Chapli Kebab',
    food_name_ur: 'چپلی کباب',
    explanation_en: 'Minced meat with spices. The cornflour binder is minimal. Main risk is deep frying in fat. Grilled version is much better.',
    explanation_ur: 'گرلڈ کباب بہتر ہے۔ نان کے بغیر کھائیں۔ تلے ہوئے سے پرہیز کریں۔',
    swap_suggestion_en: 'Grilled chapli kebab. Wrap in lettuce instead of naan.',
    swap_suggestion_ur: 'گرلڈ چپلی کباب سلاد کے ساتھ کھائیں۔',
    portion_advice: '2 pieces with green chutney. Avoid naan.',
    carbs_g: 8,
    calories_estimate: '~220 kcal',
    category: 'meat'
  },
  {
    name: 'dal chawal',
    aliases: ['dal chawal', 'lentil rice', 'dal rice', 'daal chawal'],
    risk_level: 'high',
    glycemic_index: 68,
    food_name_en: 'Dal Chawal',
    food_name_ur: 'دال چاول',
    explanation_en: 'Comfort food but white rice dominates. The dal helps slightly but not enough. Large portions common. One plate ≈ 70g carbs.',
    explanation_ur: 'دال اچھی ہے مگر چاول کم کھائیں۔ ایک پلیٹ میں 70 گرام کاربوہائیڈریٹ ہے۔',
    swap_suggestion_en: 'Dal with brown rice or quinoa. Or dal with 1 small roti.',
    swap_suggestion_ur: 'دال براؤن رائس یا ایک روٹی کے ساتھ کھائیں۔',
    portion_advice: '1 cup rice max. Double the dal amount.',
    carbs_g: 70,
    calories_estimate: '~350 kcal',
    category: 'rice'
  },
  {
    name: 'aloo paratha',
    aliases: ['aloo paratha', 'potato paratha', 'paratha', 'alu paratha'],
    risk_level: 'high',
    glycemic_index: 80,
    food_name_en: 'Aloo Paratha',
    food_name_ur: 'آلو پراٹھا',
    explanation_en: 'Potato (high GI) + maida (high GI) + fried in ghee. One of the worst combinations for diabetics. Double carb load.',
    explanation_ur: 'آلو پراٹھا شوگر کے لیے سب سے نقصان دہ ہے۔ آلو اور میدہ دونوں شوگر بڑھاتے ہیں۔',
    swap_suggestion_en: 'Gobi paratha or paneer paratha with minimal oil. Whole wheat only.',
    swap_suggestion_ur: 'گوبھی یا پنیر کا پراٹھا کم تیل میں کھائیں۔',
    portion_advice: 'ZERO. If must, half paratha with lots of yogurt.',
    carbs_g: 45,
    calories_estimate: '~320 kcal',
    category: 'bread'
  },
  {
    name: 'samosas',
    aliases: ['samosa', 'samosas', 'veg samosa', 'chicken samosa'],
    risk_level: 'high',
    glycemic_index: 75,
    food_name_en: 'Samosa',
    food_name_ur: 'سموسہ',
    explanation_en: 'Maida shell + potato filling + deep fried. Pure glucose bomb. Iftar staple but deadly for diabetics. One samosa = 20g carbs.',
    explanation_ur: 'سموسہ تلا ہوا، آلو والا، میدے کا — بالکل ممنوع۔ ایک سموسے میں 20 گرام کاربوہائیڈریٹ ہے۔',
    swap_suggestion_en: 'Baked spring rolls with chicken filling. Or air-fried samosa.',
    swap_suggestion_ur: 'بیکڈ چکن رول یا ایئر فرائیڈ سموسہ کھائیں۔',
    portion_advice: 'ZERO for diabetics. 1 small baked only if unavoidable.',
    carbs_g: 20,
    calories_estimate: '~150 kcal',
    category: 'snack'
  },
  {
    name: 'rooh afza',
    aliases: ['rooh afza', 'roohafza', 'sharbat', 'rooh afza drink'],
    risk_level: 'high',
    glycemic_index: 90,
    food_name_en: 'Rooh Afza',
    food_name_ur: 'روح افزا',
    explanation_en: 'Liquid sugar with artificial color. 1 glass = 40g sugar. Faster absorption than solid sweets. Extremely dangerous for diabetics.',
    explanation_ur: 'روح افزا میں صرف چینی ہے۔ ایک گلاس میں 40 گرام چینی۔ پانی پیئیں۔',
    swap_suggestion_en: 'Water with lemon and mint. Or chia seed drink with stevia.',
    swap_suggestion_ur: 'لیمن پانی یا تخم ملنگا کا شربت پیئیں۔',
    portion_advice: 'NEVER for diabetics.',
    carbs_g: 40,
    calories_estimate: '~160 kcal',
    category: 'drink'
  },
  {
    name: 'seekh kebab',
    aliases: ['seekh kebab', 'seekh kabab', 'beef seekh', 'chicken seekh'],
    risk_level: 'low',
    glycemic_index: 10,
    food_name_en: 'Seekh Kebab',
    food_name_ur: 'سیکھ کباب',
    explanation_en: 'Pure meat + spices. Zero carbs if no filler. Excellent protein for diabetics. Grilled, not fried.',
    explanation_ur: 'سیکھ کباب بہترین ہے۔ کاربوہائیڈریٹ نہیں، پروٹین زیادہ ہے۔ سلاد کے ساتھ کھائیں۔',
    swap_suggestion_en: 'Already optimal. Grill, do not deep fry.',
    swap_suggestion_ur: 'پہلے سے بہترین ہے۔ گرل کر کے کھائیں۔',
    portion_advice: '3-4 pieces with salad. Perfect dinner.',
    carbs_g: 2,
    calories_estimate: '~180 kcal',
    category: 'meat'
  },
  {
    name: 'zarda',
    aliases: ['zarda', 'meethe chawal', 'sweet rice', 'zarda rice'],
    risk_level: 'high',
    glycemic_index: 88,
    food_name_en: 'Zarda',
    food_name_ur: 'زردہ',
    explanation_en: 'Sweetened rice with food coloring. Eid special but pure sugar. One plate ≈ 80g sugar. Extremely high glycemic load.',
    explanation_ur: 'زردہ صرف چاول اور چینی ہے۔ مکمل طور پر ممنوع۔ ایک پلیٹ میں 80 گرام چینی۔',
    swap_suggestion_en: 'Sugar-free kheer with stevia. Or fruit salad.',
    swap_suggestion_ur: 'بغیر چینی کی کھیر یا فروٹ چاٹ کھائیں۔',
    portion_advice: 'ZERO for diabetics. If must, 2 spoons only.',
    carbs_g: 80,
    calories_estimate: '~350 kcal',
    category: 'dessert'
  },
  {
    name: 'tandoori chicken',
    aliases: ['tandoori chicken', 'bbq chicken', 'tikka', 'chicken tikka'],
    risk_level: 'low',
    glycemic_index: 5,
    food_name_en: 'Tandoori Chicken',
    food_name_ur: 'تندوری چکن',
    explanation_en: 'Chicken marinated in yogurt and spices. Zero carbs. High protein. Tandoor cooking removes fat. Perfect diabetic meal.',
    explanation_ur: 'تندوری چکن بہترین ہے۔ کاربوہائیڈریٹ نہیں، پروٹین زیادہ۔ چمڑہ اتار کر کھائیں۔',
    swap_suggestion_en: 'Already optimal. Remove skin for less fat.',
    swap_suggestion_ur: 'پہلے سے بہترین ہے۔ چمڑے کے بغیر کھائیں۔',
    portion_advice: '2 pieces (drumstick + breast). With green chutney.',
    carbs_g: 2,
    calories_estimate: '~250 kcal',
    category: 'meat'
  },
  {
    name: 'kheer',
    aliases: ['kheer', 'rice pudding', 'doodh ki kheer', 'kheer recipe'],
    risk_level: 'high',
    glycemic_index: 82,
    food_name_en: 'Kheer',
    food_name_ur: 'کھیر',
    explanation_en: 'Rice + milk + sugar. Slow cooked means high GI. Eid dessert but dangerous. One cup ≈ 50g sugar + 30g carbs from rice.',
    explanation_ur: 'کھیر میں چینی اور چاول دونوں ہیں۔ ممنوع۔ ایک کپ میں 50 گرام چینی ہے۔',
    swap_suggestion_en: 'Sugar-free kheer with stevia and brown rice. Half portion.',
    swap_suggestion_ur: 'بغیر چینی کی کھیر سٹیویا سے بنائیں۔ آدھا کپ کھائیں۔',
    portion_advice: 'ZERO. Sugar-free version: half cup.',
    carbs_g: 45,
    calories_estimate: '~280 kcal',
    category: 'dessert'
  },
  {
    name: 'pakora',
    aliases: ['pakora', 'pakoda', 'bhajiya', 'veg pakora', 'onion pakora'],
    risk_level: 'high',
    glycemic_index: 65,
    food_name_en: 'Pakora',
    food_name_ur: 'پکوڑا',
    explanation_en: 'Gram flour + vegetables + deep fried. The besan is moderate but frying + large portions hurt. Rainy day favorite but dangerous.',
    explanation_ur: 'پکوڑے تلے ہوئے ہیں۔ ایئر فرائیڈ کم نقصان دہ ہیں۔ بارش میں پرہیز کریں۔',
    swap_suggestion_en: 'Air-fried pakora or baked vegetable fritters.',
    swap_suggestion_ur: 'ایئر فرائیڈ پکوڑے کھائیں۔',
    portion_advice: '3-4 small pieces if air-fried. Avoid deep fried.',
    carbs_g: 15,
    calories_estimate: '~120 kcal',
    category: 'snack'
  },
  {
    name: 'chapati',
    aliases: ['chapati', 'roti', 'phulka', 'tandoori roti', 'roti bread'],
    risk_level: 'medium',
    glycemic_index: 62,
    food_name_en: 'Chapati/Roti',
    food_name_ur: 'روٹی',
    explanation_en: 'Whole wheat is better than maida but still high GI. Pakistani rotis are large (60-80g each). One roti ≈ 15-20g carbs.',
    explanation_ur: 'روٹی اچھی ہے مگر ایک سے زیادہ نہ کھائیں۔ ایک روٹی میں 15-20 گرام کاربوہائیڈریٹ ہے۔',
    swap_suggestion_en: 'Multigrain roti or mix atta (jowar, bajra, wheat).',
    swap_suggestion_ur: 'ملٹی گرین آٹے کی روٹی کھائیں۔',
    portion_advice: '1 small roti per meal. Not 3-4.',
    carbs_g: 18,
    calories_estimate: '~100 kcal',
    category: 'bread'
  },
  {
    name: 'salan',
    aliases: ['salan', 'curry', 'gravy', 'chicken salan', 'meat curry'],
    risk_level: 'low',
    glycemic_index: 15,
    food_name_en: 'Salan/Curry',
    food_name_ur: 'سالن',
    explanation_en: 'Meat curry with spices and tomatoes. The gravy itself is low carb. Danger is the oil and eating too much roti with it.',
    explanation_ur: 'سالن ٹھیک ہے مگر روٹی کم کھائیں۔ تیل کم ڈالیں۔',
    swap_suggestion_en: 'Already good. Use less oil. More gravy, less roti.',
    swap_suggestion_ur: 'پہلے سے اچھا ہے۔ تیل کم، سالن زیادہ کھائیں۔',
    portion_advice: '1 cup curry with 1 roti. Load up on gravy.',
    carbs_g: 8,
    calories_estimate: '~200 kcal',
    category: 'meat'
  },
  {
    name: 'raita',
    aliases: ['raita', 'yogurt dip', 'bund raita', 'cucumber raita'],
    risk_level: 'low',
    glycemic_index: 15,
    food_name_en: 'Raita',
    food_name_ur: 'رائتہ',
    explanation_en: 'Yogurt + vegetables + spices. Probiotics help gut health. Eating with meals slows glucose absorption. Essential with biryani.',
    explanation_ur: 'رائتہ ہر کھانے کے ساتھ لازمی ہے۔ شوگر بڑھنے کو روکتا ہے۔',
    swap_suggestion_en: 'Already optimal. Use fresh dahi, not sweetened.',
    swap_suggestion_ur: 'پہلے سے بہترین ہے۔ تازہ دہی استعمال کریں۔',
    portion_advice: '1 bowl with every meal. Especially with biryani.',
    carbs_g: 5,
    calories_estimate: '~60 kcal',
    category: 'dairy'
  },
  {
    name: 'dates',
    aliases: ['dates', 'khajoor', 'ajwa', 'sukri', 'khajur'],
    risk_level: 'medium',
    glycemic_index: 42,
    food_name_en: 'Dates',
    food_name_ur: 'کھجور',
    explanation_en: 'Natural sugar but high density. Ramadan essential but 1 date = 5g sugar. 3 dates = 15g sugar. Eat with nuts to slow absorption.',
    explanation_ur: 'کھجور اچھی ہے مگر دو سے زیادہ نہ کھائیں۔ تین کھجور میں 15 گرام چینی ہے۔',
    swap_suggestion_en: '1-2 dates only. With nuts to slow absorption.',
    swap_suggestion_ur: '1-2 کھجور بادام کے ساتھ کھائیں۔',
    portion_advice: 'Max 2 dates at iftar. Not 7-10.',
    carbs_g: 15,
    calories_estimate: '~70 kcal',
    category: 'fruit'
  },
  {
    name: 'oats',
    aliases: ['oats', 'oatmeal', 'daliya', 'porridge'],
    risk_level: 'low',
    glycemic_index: 55,
    food_name_en: 'Oats',
    food_name_ur: 'اوٹس',
    explanation_en: 'Steel-cut oats are low GI. Pakistani market oats are often instant (high GI). Check packaging. Good breakfast for diabetics.',
    explanation_ur: 'اوٹس اچھا ناشتہ ہے۔ انسٹنٹ والا نہیں، سٹیل کٹ اوٹس استعمال کریں۔',
    swap_suggestion_en: 'Steel-cut or rolled oats. Avoid flavored instant oats.',
    swap_suggestion_ur: 'سادہ اوٹس دار چینی کے ساتھ کھائیں۔',
    portion_advice: 'Half cup dry = 1 cup cooked. Add nuts and cinnamon.',
    carbs_g: 27,
    calories_estimate: '~150 kcal',
    category: 'breakfast'
  },
  {
    name: 'eggs',
    aliases: ['eggs', 'omelette', 'boiled egg', 'fried egg', 'anda'],
    risk_level: 'low',
    glycemic_index: 0,
    food_name_en: 'Eggs',
    food_name_ur: 'انڈے',
    explanation_en: 'Zero carbs. Perfect protein. Boiled is best. Fried adds unnecessary fat. 2 eggs = 12g protein, 0g carbs.',
    explanation_ur: 'انڈے شوگر نہیں بڑھاتے۔ روزانہ دو انڈے کھائیں۔ ابلے ہوئے بہترین ہیں۔',
    swap_suggestion_en: 'Already optimal. Boiled or poached preferred.',
    swap_suggestion_ur: 'پہلے سے بہترین ہے۔ ابلے ہوئے کھائیں۔',
    portion_advice: '2-3 eggs daily. Anytime meal.',
    carbs_g: 0,
    calories_estimate: '~140 kcal',
    category: 'breakfast'
  },
  {
    name: 'daal',
    aliases: ['daal', 'dal', 'lentils', 'moong daal', 'masoor daal', 'chana daal'],
    risk_level: 'low',
    glycemic_index: 30,
    food_name_en: 'Daal (Lentils)',
    food_name_ur: 'دال',
    explanation_en: 'All lentils are low GI, high fiber, high protein. The staple of diabetic-friendly Pakistani diet. One cup = 15g protein.',
    explanation_ur: 'دالیں شوگر کے لیے بہترین ہیں۔ روزانہ کھائیں۔ فائبر اور پروٹین زیادہ ہے۔',
    swap_suggestion_en: 'Already optimal. Any dal is good. Avoid too much oil baghaar.',
    swap_suggestion_ur: 'پہلے سے بہترین ہے۔ تیل کا بگھار کم ڈالیں۔',
    portion_advice: '1 cup dal + 1 roti = perfect meal.',
    carbs_g: 27,
    calories_estimate: '~180 kcal',
    category: 'lentils'
  },
  {
    name: 'chana',
    aliases: ['chana', 'chickpeas', 'boiled chana', 'chanay', 'kabuli chana'],
    risk_level: 'low',
    glycemic_index: 28,
    food_name_en: 'Chana (Chickpeas)',
    food_name_ur: 'چنے',
    explanation_en: 'Highest fiber legume. Extremely filling. The protein and fiber combo is perfect for blood sugar control. One cup = 12g fiber.',
    explanation_ur: 'چنے سب سے بہترین ہیں۔ بھنے ہوئے یا ابلے ہوئے کھائیں۔ فائبر بہت زیادہ ہے۔',
    swap_suggestion_en: 'Already optimal. Boiled better than fried.',
    swap_suggestion_ur: 'پہلے سے بہترین ہے۔ ابلے ہوئے کھائیں۔',
    portion_advice: '1 cup boiled = snack or meal.',
    carbs_g: 27,
    calories_estimate: '~160 kcal',
    category: 'lentils'
  },
  {
    name: 'palak',
    aliases: ['palak', 'spinach', 'saag', 'palak paneer'],
    risk_level: 'low',
    glycemic_index: 15,
    food_name_en: 'Palak (Spinach)',
    food_name_ur: 'پالک',
    explanation_en: 'Iron, magnesium, fiber. Cooked with minimal oil. Excellent for diabetics. Magnesium improves insulin sensitivity.',
    explanation_ur: 'پالک روزانہ کھائیں۔ شوگر کنٹرول میں مدد دیتی ہے۔ میگنیشیم انسولین بہتر کرتا ہے۔',
    swap_suggestion_en: 'Already optimal. Fresh > frozen > canned.',
    swap_suggestion_ur: 'پہلے سے بہترین ہے۔ تازہ پالک استعمال کریں۔',
    portion_advice: 'Unlimited. Eat daily.',
    carbs_g: 3,
    calories_estimate: '~40 kcal',
    category: 'vegetables'
  },
  {
    name: 'karela',
    aliases: ['karela', 'karela juice', 'bitter gourd', 'karela sabzi'],
    risk_level: 'low',
    glycemic_index: 15,
    food_name_en: 'Karela (Bitter Gourd)',
    food_name_ur: 'کریلا',
    explanation_en: 'Contains charantin and polypeptide-p which mimic insulin. Traditional Pakistani diabetic remedy with scientific backing.',
    explanation_ur: 'کریلا قدرتی انسولین ہے۔ روزانہ کھائیں۔ خالی پیٹ جوس پئیں۔',
    swap_suggestion_en: 'Already optimal. Juice on empty stomach or cooked vegetable.',
    swap_suggestion_ur: 'پہلے سے بہترین ہے۔ صبح خالی پیٹ جوس پیئیں۔',
    portion_advice: 'Half karela cooked daily. Or 30ml juice morning.',
    carbs_g: 4,
    calories_estimate: '~25 kcal',
    category: 'vegetables'
  },
  {
    name: 'jamun',
    aliases: ['jamun', 'jaman', 'black plum', 'java plum'],
    risk_level: 'low',
    glycemic_index: 25,
    food_name_en: 'Jamun (Black Plum)',
    food_name_ur: 'جامن',
    explanation_en: 'Jamun fruit and seeds are traditional diabetic medicine in Pakistan. Low GI, helps insulin sensitivity. Seasonal superfood.',
    explanation_ur: 'جامن شوگر کے لیے دوا ہے۔ موسم میں ضرور کھائیں۔ بیج بھی فائدہ مند ہیں۔',
    swap_suggestion_en: 'Already optimal. Seasonal fruit, stock up.',
    swap_suggestion_ur: 'پہلے سے بہترین ہے۔ موسم میں روزانہ کھائیں۔',
    portion_advice: '10-15 fruits daily when in season.',
    carbs_g: 15,
    calories_estimate: '~60 kcal',
    category: 'fruit'
  },
  {
    name: 'methi',
    aliases: ['methi', 'methi dana', 'fenugreek', 'fenugreek seeds'],
    risk_level: 'low',
    glycemic_index: 0,
    food_name_en: 'Methi (Fenugreek)',
    food_name_ur: 'میتھی دانہ',
    explanation_en: 'Soaked methi dana water is proven to reduce fasting glucose by 25% in studies. Pakistani household remedy. Rich in soluble fiber.',
    explanation_ur: 'میتھی دانا پانی میں بھگو کر پئیں۔ شوگر 25% تک کم کرتا ہے۔',
    swap_suggestion_en: 'Already optimal. Soak 1 tsp overnight, drink water morning.',
    swap_suggestion_ur: 'پہلے سے بہترین ہے۔ رات کو بھگو کر صبح پئیں۔',
    portion_advice: '1 tsp soaked seeds daily. Water + seeds both consumed.',
    carbs_g: 0,
    calories_estimate: '~5 kcal',
    category: 'herbs'
  },
  {
    name: 'neem',
    aliases: ['neem', 'neem leaves', 'neem powder', 'neem patta'],
    risk_level: 'low',
    glycemic_index: 0,
    food_name_en: 'Neem Leaves',
    food_name_ur: 'نیم کے پتے',
    explanation_en: 'Azadirachtin in neem increases insulin receptor sensitivity. Used in traditional Pakistani medicine for centuries.',
    explanation_ur: 'نیم کے پتے صبح خالی پیٹ چبانے سے شوگر کنٹرول ہوتی ہے۔',
    swap_suggestion_en: 'Already optimal. 4-5 leaves chewed morning empty stomach.',
    swap_suggestion_ur: 'پہلے سے بہترین ہے۔ 4-5 پتے روزانہ صبح چبائیں۔',
    portion_advice: '4-5 fresh leaves daily. Or 1 tsp powder.',
    carbs_g: 0,
    calories_estimate: '~2 kcal',
    category: 'herbs'
  },
  {
    name: 'chai',
    aliases: ['chai', 'tea', 'doodh patti', 'chaye', 'karak chai'],
    risk_level: 'medium',
    glycemic_index: 40,
    food_name_en: 'Chai (Tea)',
    food_name_ur: 'چائے',
    explanation_en: 'With sugar: high risk (2 tsp = 10g sugar). Without sugar: low risk. Doodh patti has milk sugar (lactose). Use stevia or skip sugar.',
    explanation_ur: 'چینی والی چائے نقصان دہ ہے۔ بغیر چینی پیئیں یا سٹیویا استعمال کریں۔',
    swap_suggestion_en: 'Green tea or black tea without sugar. Or cinnamon tea.',
    swap_suggestion_ur: 'گرین ٹی یا دار چینی کی چائے پیئیں۔',
    portion_advice: '2 cups max daily. Always without sugar.',
    carbs_g: 10,
    calories_estimate: '~40 kcal',
    category: 'drink'
  },
  {
    name: 'pizza',
    aliases: ['pizza', 'cheese pizza', 'fast food', 'burger'],
    risk_level: 'high',
    glycemic_index: 80,
    food_name_en: 'Pizza/Burger',
    food_name_ur: 'پیزا/برگر',
    explanation_en: 'Refined flour base + processed cheese + sugary sauce. One slice = 35g carbs. The fat delays but magnifies the glucose spike 3-5 hours later.',
    explanation_ur: 'میدے کی روٹی، پروسیسڈ چیز، اور میٹھی ساس — شوگر کے لیے بہت نقصان دہ۔',
    swap_suggestion_en: 'Homemade whole wheat pizza with vegetables. Thin crust only.',
    swap_suggestion_ur: 'گھر پر ہول ویٹ پیزا سبزیوں کے ساتھ بنائیں۔',
    portion_advice: '1 small slice if whole wheat. Avoid fast food chains.',
    carbs_g: 35,
    calories_estimate: '~285 kcal',
    category: 'snack'
  },
  {
    name: 'mango',
    aliases: ['mango', 'aam', 'mangoes', 'aam fruit'],
    risk_level: 'high',
    glycemic_index: 56,
    food_name_en: 'Mango',
    food_name_ur: 'آم',
    explanation_en: 'King of fruits but high natural sugar. One medium mango = 45g sugar. Very easy to overeat. Seasonal danger for diabetics.',
    explanation_ur: 'آم میں بہت زیادہ قدرتی چینی ہے۔ ایک آم میں 45 گرام چینی۔ زیادہ نہ کھائیں۔',
    swap_suggestion_en: 'Half a small mango with yogurt. Or switch to guava/papaya.',
    swap_suggestion_ur: 'آدھا چھوٹا آم دہی کے ساتھ کھائیں۔ یا امرود کھائیں۔',
    portion_advice: 'Half small mango max. Not daily.',
    carbs_g: 45,
    calories_estimate: '~200 kcal',
    category: 'fruit'
  },
  {
    name: 'golgappa',
    aliases: ['golgappa', 'pani puri', 'gol gappa', 'panipuri'],
    risk_level: 'medium',
    glycemic_index: 60,
    food_name_en: 'Golgappa/Pani Puri',
    food_name_ur: 'گول گپے',
    explanation_en: 'Fried puri + potato + sweet chutney. The small size is deceptive — 6 pieces = 40g carbs. The sweet water adds hidden sugar.',
    explanation_ur: 'چھوٹے ہیں مگر 6 گول گپوں میں 40 گرام کاربوہائیڈریٹ ہے۔ میٹھا پانی نقصان دہ ہے۔',
    swap_suggestion_en: 'Limit to 3 pieces. Skip the sweet water. Add extra chickpeas.',
    swap_suggestion_ur: 'صرف 3 گول گپے کھائیں۔ میٹھا پانی نہ پیئیں۔',
    portion_advice: 'Max 3 pieces. Once a month.',
    carbs_g: 40,
    calories_estimate: '~200 kcal',
    category: 'snack'
  },
  {
    name: 'pulao',
    aliases: ['pulao', 'pilaf', 'rice', 'chicken pulao', 'beef pulao'],
    risk_level: 'high',
    glycemic_index: 65,
    food_name_en: 'Pulao',
    food_name_ur: 'پلاؤ',
    explanation_en: 'Rice cooked in broth. Still high GI white rice. The meat adds protein but rice dominates. One plate ≈ 60g carbs.',
    explanation_ur: 'چاول کی وجہ سے شوگر بڑھتی ہے۔ ایک پلیٹ میں 60 گرام کاربوہائیڈریٹ ہے۔',
    swap_suggestion_en: 'Brown rice pulao or quinoa pulao. Half portion with extra meat.',
    swap_suggestion_ur: 'براؤن رائس پلاؤ کھائیں۔ آدھی پلیٹ لیں۔',
    portion_advice: '1 cup rice max. Double the meat.',
    carbs_g: 60,
    calories_estimate: '~380 kcal',
    category: 'rice'
  },
  {
    name: 'chicken karahi',
    aliases: ['chicken karahi', 'karahi', 'karahi chicken', 'karahi gosht'],
    risk_level: 'low',
    glycemic_index: 10,
    food_name_en: 'Chicken Karahi',
    food_name_ur: 'چکن کڑاہی',
    explanation_en: 'Tomato-based curry with chicken. Low carb, high protein. The tomatoes add lycopene. Oil quantity is the main concern.',
    explanation_ur: 'ٹماٹر والا سالن کم کاربوہائیڈریٹ ہے۔ تیل کم ڈالیں۔',
    swap_suggestion_en: 'Already good. Use less oil. Eat with 1 small roti.',
    swap_suggestion_ur: 'پہلے سے اچھا ہے۔ تیل کم کریں۔',
    portion_advice: '1 cup curry + 1 roti. Add salad.',
    carbs_g: 8,
    calories_estimate: '~250 kcal',
    category: 'meat'
  },
  {
    name: 'mutton karahi',
    aliases: ['mutton karahi', 'gosht karahi', 'lamb karahi'],
    risk_level: 'low',
    glycemic_index: 10,
    food_name_en: 'Mutton Karahi',
    food_name_ur: 'مٹن کڑاہی',
    explanation_en: 'Mutton in spiced tomato gravy. Low carb, high protein and iron. The fat content is higher than chicken. Good for diabetics in moderation.',
    explanation_ur: 'مٹن پروٹین سے بھرپور ہے۔ تیل کم ڈالیں۔',
    swap_suggestion_en: 'Already good. Trim visible fat. Use less oil in cooking.',
    swap_suggestion_ur: 'پہلے سے اچھا ہے۔ چربی ہٹا کر پکائیں۔',
    portion_advice: '1 cup with 1 roti. Once a week.',
    carbs_g: 6,
    calories_estimate: '~320 kcal',
    category: 'meat'
  },
  {
    name: 'qorma',
    aliases: ['qorma', 'korma', 'chicken qorma', 'mutton qorma'],
    risk_level: 'medium',
    glycemic_index: 20,
    food_name_en: 'Qorma',
    food_name_ur: 'قورمہ',
    explanation_en: 'Yogurt-based creamy curry. Moderate carbs from yogurt. High fat from oil and cream. Rich dish for special occasions.',
    explanation_ur: 'دہی والا سالن درمیانہ خطرہ۔ تیل اور کریم زیادہ ہے۔',
    swap_suggestion_en: 'Use low-fat yogurt. Skip cream. More spices, less oil.',
    swap_suggestion_ur: 'کم چکنائی والا دہی استعمال کریں۔ کریم نہ ڈالیں۔',
    portion_advice: '1 cup. Special occasions only.',
    carbs_g: 10,
    calories_estimate: '~350 kcal',
    category: 'meat'
  },
  {
    name: 'tikka boti',
    aliases: ['tikka boti', 'chicken tikka boti', 'beef tikka', 'boti'],
    risk_level: 'low',
    glycemic_index: 5,
    food_name_en: 'Tikka Boti',
    food_name_ur: 'تکہ بوٹی',
    explanation_en: 'Grilled marinated meat cubes. Zero carbs, high protein. Charcoal grilling removes fat. Perfect diabetic meal.',
    explanation_ur: 'گرلڈ گوشت بہترین ہے۔ کاربوہائیڈریٹ نہیں۔',
    swap_suggestion_en: 'Already optimal. Eat with green chutney and salad.',
    swap_suggestion_ur: 'پہلے سے بہترین ہے۔ ہری چٹنی اور سلاد کے ساتھ کھائیں۔',
    portion_advice: '6-8 pieces. Great dinner option.',
    carbs_g: 2,
    calories_estimate: '~200 kcal',
    category: 'meat'
  },
  {
    name: 'malai boti',
    aliases: ['malai boti', 'cream boti', 'malai tikka'],
    risk_level: 'medium',
    glycemic_index: 10,
    food_name_en: 'Malai Boti',
    food_name_ur: 'ملائی بوٹی',
    explanation_en: 'Cream-marinated grilled meat. Low carb but high saturated fat from cream. Better than fried but watch cholesterol.',
    explanation_ur: 'کریم والی بوٹی میں چکنائی زیادہ ہے۔ ہفتے میں ایک بار کھائیں۔',
    swap_suggestion_en: 'Tikka boti (no cream) is better. Or use yogurt marinade instead.',
    swap_suggestion_ur: 'سادہ تکہ بوٹی بہتر ہے۔ دہی کا میرینیشن کریں۔',
    portion_advice: '4-5 pieces. Once a week.',
    carbs_g: 4,
    calories_estimate: '~280 kcal',
    category: 'meat'
  },
  {
    name: 'fish fry',
    aliases: ['fish fry', 'fried fish', 'tali machli'],
    risk_level: 'medium',
    glycemic_index: 25,
    food_name_en: 'Fried Fish',
    food_name_ur: 'تلی ہوئی مچھلی',
    explanation_en: 'Fish is healthy (omega-3) but frying adds carbs from batter and fat from oil. Grilled fish is much better.',
    explanation_ur: 'مچھلی اچھی ہے مگر تلنے سے نقصان دہ ہو جاتی ہے۔',
    swap_suggestion_en: 'Grilled or baked fish with lemon and herbs.',
    swap_suggestion_ur: 'گرلڈ مچھلی لیموں کے ساتھ کھائیں۔',
    portion_advice: '1 piece grilled. Avoid fried batter.',
    carbs_g: 15,
    calories_estimate: '~300 kcal',
    category: 'meat'
  },
  {
    name: 'grilled fish',
    aliases: ['grilled fish', 'baked fish', 'machli', 'fish tikka'],
    risk_level: 'low',
    glycemic_index: 5,
    food_name_en: 'Grilled Fish',
    food_name_ur: 'گرلڈ مچھلی',
    explanation_en: 'Rich in omega-3 fatty acids. Zero carbs. Reduces inflammation and improves insulin sensitivity. Eat twice a week.',
    explanation_ur: 'مچھلی میں اومیگا-3 ہے۔ شوگر کنٹرول میں مدد دیتی ہے۔',
    swap_suggestion_en: 'Already optimal. Salmon, tuna, or local river fish all excellent.',
    swap_suggestion_ur: 'پہلے سے بہترین ہے۔ ہفتے میں دو بار کھائیں۔',
    portion_advice: '1 fillet (150g). Twice a week.',
    carbs_g: 0,
    calories_estimate: '~180 kcal',
    category: 'meat'
  },
  {
    name: 'aloo gobi',
    aliases: ['aloo gobi', 'potato cauliflower', 'alu gobi'],
    risk_level: 'medium',
    glycemic_index: 45,
    food_name_en: 'Aloo Gobi',
    food_name_ur: 'آلو گوبھی',
    explanation_en: 'Potato raises GI. Cauliflower lowers it. The combination is moderate. More gobi, less aloo is the key.',
    explanation_ur: 'آلو شوگر بڑھاتا ہے۔ گوبھی زیادہ، آلو کم ڈالیں۔',
    swap_suggestion_en: 'Gobi-only version. Or replace potato with turnip (shaljam).',
    swap_suggestion_ur: 'صرف گوبھی کا سالن بنائیں۔ آلو نہ ڈالیں۔',
    portion_advice: '1 cup. More gobi than aloo.',
    carbs_g: 20,
    calories_estimate: '~150 kcal',
    category: 'vegetables'
  },
  {
    name: 'bhindi',
    aliases: ['bhindi', 'okra', 'ladyfinger', 'bhindi sabzi'],
    risk_level: 'low',
    glycemic_index: 20,
    food_name_en: 'Bhindi (Okra)',
    food_name_ur: 'بھنڈی',
    explanation_en: 'High soluble fiber slows glucose absorption. Rich in magnesium which improves insulin sensitivity. Excellent diabetic vegetable.',
    explanation_ur: 'بھنڈی کا فائبر شوگر جذب ہونے سے روکتا ہے۔ بہترین سبزی ہے۔',
    swap_suggestion_en: 'Already optimal. Cook with minimal oil. Avoid deep frying.',
    swap_suggestion_ur: 'پہلے سے بہترین ہے۔ کم تیل میں پکائیں۔',
    portion_advice: 'Unlimited. Daily consumption encouraged.',
    carbs_g: 7,
    calories_estimate: '~50 kcal',
    category: 'vegetables'
  },
  {
    name: 'baingan',
    aliases: ['baingan', 'eggplant', 'brinjal', 'bengan'],
    risk_level: 'low',
    glycemic_index: 15,
    food_name_en: 'Baingan (Eggplant)',
    food_name_ur: 'بینگن',
    explanation_en: 'Very low carb. High fiber. Nasunin in eggplant protects pancreatic beta cells. Excellent for diabetics.',
    explanation_ur: 'بینگن میں فائبر زیادہ، کاربوہائیڈریٹ کم ہے۔ شوگر کے لیے بہترین۔',
    swap_suggestion_en: 'Already optimal. Grill or roast instead of frying.',
    swap_suggestion_ur: 'پہلے سے بہترین ہے۔ تلنے کی بجائے بھون کر کھائیں۔',
    portion_advice: 'Unlimited. Great in salan or bharta.',
    carbs_g: 6,
    calories_estimate: '~35 kcal',
    category: 'vegetables'
  },
  {
    name: 'lobia',
    aliases: ['lobia', 'black eyed peas', 'lobia sabzi', 'raungi'],
    risk_level: 'low',
    glycemic_index: 33,
    food_name_en: 'Lobia (Black Eyed Peas)',
    food_name_ur: 'لوبیا',
    explanation_en: 'Low GI legume. High protein + fiber. One cup = 13g protein. Very filling, stable glucose release.',
    explanation_ur: 'لوبیا پروٹین اور فائبر سے بھرپور ہے۔ شوگر آہستہ بڑھتی ہے۔',
    swap_suggestion_en: 'Already optimal. Cook with tomatoes and minimal oil.',
    swap_suggestion_ur: 'پہلے سے بہترین ہے۔ ٹماٹر کے ساتھ پکائیں۔',
    portion_advice: '1 cup cooked. Perfect with 1 roti.',
    carbs_g: 22,
    calories_estimate: '~130 kcal',
    category: 'lentils'
  },
  {
    name: 'matar pulao',
    aliases: ['matar pulao', 'pea pulao', 'matar rice'],
    risk_level: 'high',
    glycemic_index: 65,
    food_name_en: 'Matar Pulao',
    food_name_ur: 'مٹر پلاؤ',
    explanation_en: 'White rice with peas. The peas add fiber but rice dominates. One plate ≈ 55g carbs. Better than plain rice but still high.',
    explanation_ur: 'مٹر فائبر دیتے ہیں مگر چاول پھر بھی شوگر بڑھاتے ہیں۔',
    swap_suggestion_en: 'Brown rice matar pulao. Or cauliflower rice with peas.',
    swap_suggestion_ur: 'براؤن رائس کا مٹر پلاؤ بنائیں۔',
    portion_advice: '1 cup max. Add extra peas.',
    carbs_g: 55,
    calories_estimate: '~300 kcal',
    category: 'rice'
  },
  {
    name: 'shahi tukra',
    aliases: ['shahi tukra', 'shahi tukda', 'bread pudding'],
    risk_level: 'high',
    glycemic_index: 85,
    food_name_en: 'Shahi Tukra',
    food_name_ur: 'شاہی ٹکڑا',
    explanation_en: 'Fried bread + sugar syrup + rabri. Triple sugar hit. One piece = 35g sugar. Eid special, extremely dangerous.',
    explanation_ur: 'تلی ہوئی بریڈ + چینی + ربڑی — شوگر کا بم۔ ایک ٹکڑے میں 35 گرام چینی۔',
    swap_suggestion_en: 'Sugar-free bread pudding with stevia and low-fat milk.',
    swap_suggestion_ur: 'بغیر چینی کی بریڈ پڈنگ بنائیں۔',
    portion_advice: 'ZERO for diabetics.',
    carbs_g: 35,
    calories_estimate: '~250 kcal',
    category: 'dessert'
  },
  {
    name: 'jalebi',
    aliases: ['jalebi', 'jalebi sweet', 'jalabi'],
    risk_level: 'high',
    glycemic_index: 90,
    food_name_en: 'Jalebi',
    food_name_ur: 'جلیبی',
    explanation_en: 'Deep fried batter soaked in sugar syrup. Pure glucose. One jalebi = 20g sugar. Absorbed in minutes.',
    explanation_ur: 'جلیبی تلی ہوئی اور چینی میں ڈوبی ہوئی — شوگر کے لیے زہر۔',
    swap_suggestion_en: 'None. Avoid completely. If craving, 1 small bite.',
    swap_suggestion_ur: 'کوئی متبادل نہیں۔ مکمل پرہیز کریں۔',
    portion_advice: 'ZERO. Never.',
    carbs_g: 20,
    calories_estimate: '~150 kcal',
    category: 'dessert'
  },
  {
    name: 'barfi',
    aliases: ['barfi', 'burfi', 'mithai barfi', 'khoya barfi'],
    risk_level: 'high',
    glycemic_index: 75,
    food_name_en: 'Barfi',
    food_name_ur: 'برفی',
    explanation_en: 'Condensed milk + sugar. High fat + high sugar. One piece = 18g sugar + 10g fat. Very calorie dense.',
    explanation_ur: 'برفی میں دودھ اور چینی دونوں ہیں۔ ایک پیس میں 18 گرام چینی۔',
    swap_suggestion_en: 'Sugar-free barfi made with stevia and almond flour.',
    swap_suggestion_ur: 'سٹیویا اور بادام کے آٹے کی برفی بنائیں۔',
    portion_advice: 'ZERO. Sugar-free version: 1 small piece.',
    carbs_g: 18,
    calories_estimate: '~160 kcal',
    category: 'dessert'
  },
  {
    name: 'ras malai',
    aliases: ['ras malai', 'rasmalai', 'milk sweet'],
    risk_level: 'high',
    glycemic_index: 70,
    food_name_en: 'Ras Malai',
    food_name_ur: 'رس ملائی',
    explanation_en: 'Cheese balls in sweetened milk. High protein from cheese but high sugar from syrup. 2 pieces = 25g sugar.',
    explanation_ur: 'پنیر اچھا ہے مگر چینی کی مقدار بہت زیادہ ہے۔',
    swap_suggestion_en: 'Homemade with stevia and low-fat milk. 1 piece only.',
    swap_suggestion_ur: 'سٹیویا سے گھر پر بنائیں۔ ایک پیس کافی ہے۔',
    portion_advice: '1 piece if sugar-free. Avoid regular.',
    carbs_g: 25,
    calories_estimate: '~200 kcal',
    category: 'dessert'
  },
  {
    name: 'falooda',
    aliases: ['falooda', 'faluda', 'ice cream falooda'],
    risk_level: 'high',
    glycemic_index: 70,
    food_name_en: 'Falooda',
    food_name_ur: 'فالودہ',
    explanation_en: 'Vermicelli + ice cream + syrup + milk. Multiple sugar sources. One glass = 50g sugar. Summer favorite but dangerous.',
    explanation_ur: 'فالودے میں چینی کے کئی ذرائع ہیں۔ ایک گلاس میں 50 گرام چینی۔',
    swap_suggestion_en: 'Chia seed drink with stevia and rose water. Or sugar-free kulfi.',
    swap_suggestion_ur: 'تخم ملنگا کا شربت سٹیویا سے پیئیں۔',
    portion_advice: 'ZERO. If must, sugar-free version.',
    carbs_g: 50,
    calories_estimate: '~280 kcal',
    category: 'dessert'
  },
  {
    name: 'shami kebab sandwich',
    aliases: ['shami burger', 'kebab sandwich', 'bun kebab'],
    risk_level: 'high',
    glycemic_index: 70,
    food_name_en: 'Bun Kebab / Sandwich',
    food_name_ur: 'بن کباب',
    explanation_en: 'White bread bun + kebab. The bun is high GI refined flour. One sandwich = 45g carbs. The kebab is fine, the bun is not.',
    explanation_ur: 'سفید ڈبل روٹی شوگر بڑھاتی ہے۔ کباب ٹھیک ہے، بن نہیں۔',
    swap_suggestion_en: 'Lettuce wrap kebab. Or whole wheat bun.',
    swap_suggestion_ur: 'کباب سلاد کے پتوں میں لپیٹ کر کھائیں۔',
    portion_advice: 'Skip the bun. Eat kebab with salad.',
    carbs_g: 45,
    calories_estimate: '~350 kcal',
    category: 'snack'
  },
  {
    name: 'dahi',
    aliases: ['dahi', 'yogurt', 'curd', 'dahi plain'],
    risk_level: 'low',
    glycemic_index: 14,
    food_name_en: 'Dahi (Plain Yogurt)',
    food_name_ur: 'دہی',
    explanation_en: 'Probiotics improve gut health and insulin sensitivity. Low GI. High protein. Eat with every meal to slow glucose absorption.',
    explanation_ur: 'دہی شوگر جذب ہونے کو سست کرتا ہے۔ ہر کھانے کے ساتھ کھائیں۔',
    swap_suggestion_en: 'Already optimal. Fresh homemade dahi is best.',
    swap_suggestion_ur: 'پہلے سے بہترین ہے۔ تازہ گھر کا دہی بہترین ہے۔',
    portion_advice: '1 bowl with every meal. Unlimited.',
    carbs_g: 5,
    calories_estimate: '~60 kcal',
    category: 'dairy'
  },
  {
    name: 'paneer',
    aliases: ['paneer', 'cottage cheese', 'paneer tikka', 'paneer sabzi'],
    risk_level: 'low',
    glycemic_index: 5,
    food_name_en: 'Paneer (Cottage Cheese)',
    food_name_ur: 'پنیر',
    explanation_en: 'High protein, low carb. 100g = 18g protein, 3g carbs. Excellent for diabetics. Very filling.',
    explanation_ur: 'پنیر پروٹین سے بھرپور، کاربوہائیڈریٹ کم۔ شوگر کے لیے بہترین۔',
    swap_suggestion_en: 'Already optimal. Grill or cook in tomato gravy.',
    swap_suggestion_ur: 'پہلے سے بہترین ہے۔ ٹماٹر کے سالن میں پکائیں۔',
    portion_advice: '100g daily. Great snack or meal component.',
    carbs_g: 3,
    calories_estimate: '~260 kcal',
    category: 'dairy'
  },
  {
    name: 'chanay ki daal',
    aliases: ['chanay ki daal', 'chana dal', 'bengal gram', 'daal chana'],
    risk_level: 'low',
    glycemic_index: 8,
    food_name_en: 'Chana Dal',
    food_name_ur: 'چنے کی دال',
    explanation_en: 'Lowest GI among all dals. Extremely high fiber. The broken chickpea form releases glucose very slowly. Diabetic superfood.',
    explanation_ur: 'سب سے کم GI والی دال۔ شوگر بہت آہستہ بڑھتی ہے۔ روزانہ کھائیں۔',
    swap_suggestion_en: 'Already optimal. Cook with turmeric and minimal oil.',
    swap_suggestion_ur: 'پہلے سے بہترین ہے۔ ہلدی کے ساتھ پکائیں۔',
    portion_advice: '1 cup daily. With 1 roti.',
    carbs_g: 25,
    calories_estimate: '~140 kcal',
    category: 'lentils'
  },
  {
    name: 'brown rice',
    aliases: ['brown rice', 'brown chawal', 'whole grain rice'],
    risk_level: 'medium',
    glycemic_index: 50,
    food_name_en: 'Brown Rice',
    food_name_ur: 'براؤن رائس',
    explanation_en: 'The bran layer slows glucose absorption. GI is 50 vs 70 for white rice. Fiber + magnesium. Better choice for diabetics.',
    explanation_ur: 'براؤن رائس سفید چاول سے بہتر ہے۔ فائبر زیادہ، شوگر آہستہ بڑھتی ہے۔',
    swap_suggestion_en: 'Already a good swap for white rice. Mix with quinoa for even lower GI.',
    swap_suggestion_ur: 'سفید چاول کی بجائے براؤن رائس کھائیں۔',
    portion_advice: '1 cup cooked. Not unlimited.',
    carbs_g: 45,
    calories_estimate: '~215 kcal',
    category: 'rice'
  },
  {
    name: 'salad',
    aliases: ['salad', 'kachoomar', 'cucumber salad', 'green salad'],
    risk_level: 'low',
    glycemic_index: 15,
    food_name_en: 'Salad / Kachoomar',
    food_name_ur: 'سلاد / کچومر',
    explanation_en: 'Raw vegetables with lemon. Zero fat, high fiber, loads of vitamins. Eat before meals to reduce total glucose spike by 20%.',
    explanation_ur: 'کھانے سے پہلے سلاد کھائیں۔ شوگر 20% کم بڑھتی ہے۔',
    swap_suggestion_en: 'Already optimal. Add cucumber, tomato, onion, lemon. No dressing.',
    swap_suggestion_ur: 'پہلے سے بہترین ہے۔ کھیرا، ٹماٹر، پیاز، لیموں ڈالیں۔',
    portion_advice: '1 plate before every meal. Unlimited.',
    carbs_g: 5,
    calories_estimate: '~25 kcal',
    category: 'vegetables'
  },
  {
    name: 'mango lassi',
    aliases: ['mango lassi', 'aam lassi', 'mango shake'],
    risk_level: 'high',
    glycemic_index: 65,
    food_name_en: 'Mango Lassi',
    food_name_ur: 'آم لسی',
    explanation_en: 'Mango (45g sugar) + yogurt + sugar. Double sugar source. One glass = 55g sugar. Summer danger.',
    explanation_ur: 'آم اور چینی دونوں مل کر شوگر بہت بڑھاتے ہیں۔',
    swap_suggestion_en: 'Plain salted lassi. Or yogurt with 2 small mango cubes, no sugar.',
    swap_suggestion_ur: 'نمکین لسی پیئیں۔ آم نہ ڈالیں۔',
    portion_advice: 'AVOID. Salted lassi instead.',
    carbs_g: 55,
    calories_estimate: '~250 kcal',
    category: 'drink'
  },
  {
    name: 'green tea',
    aliases: ['green tea', 'kehwa', 'green chai', 'qehwa'],
    risk_level: 'low',
    glycemic_index: 0,
    food_name_en: 'Green Tea / Kehwa',
    food_name_ur: 'سبز چائے / قہوہ',
    explanation_en: 'Catechins in green tea improve insulin sensitivity. Zero carbs. Drink 2-3 cups daily. Kashmiri kehwa with cinnamon is excellent.',
    explanation_ur: 'سبز چائے انسولین بہتر کرتی ہے۔ دن میں 2-3 کپ پیئیں۔',
    swap_suggestion_en: 'Already optimal. Add cinnamon for extra glucose control.',
    swap_suggestion_ur: 'پہلے سے بہترین ہے۔ دار چینی ڈال کر پیئیں۔',
    portion_advice: '2-3 cups daily. Without sugar.',
    carbs_g: 0,
    calories_estimate: '~2 kcal',
    category: 'drink'
  },
  {
    name: 'lemon water',
    aliases: ['lemon water', 'lemonade', 'nimbu pani', 'lemon pani'],
    risk_level: 'low',
    glycemic_index: 5,
    food_name_en: 'Lemon Water (No Sugar)',
    food_name_ur: 'لیمن پانی (بغیر چینی)',
    explanation_en: 'Vitamin C + hydration. Lemon polyphenols slow starch digestion. Drink before meals to reduce glucose spike. Zero calories.',
    explanation_ur: 'لیمن پانی شوگر جذب ہونے کو کم کرتا ہے۔ کھانے سے پہلے پیئیں۔',
    swap_suggestion_en: 'Already optimal. Add mint and a pinch of black salt.',
    swap_suggestion_ur: 'پہلے سے بہترین ہے۔ پودینہ اور کالا نمک ڈالیں۔',
    portion_advice: '1-2 glasses before meals. Unlimited.',
    carbs_g: 2,
    calories_estimate: '~8 kcal',
    category: 'drink'
  },
  {
    name: 'chaat',
    aliases: ['chaat', 'aloo chaat', 'papri chaat', 'dahi chaat'],
    risk_level: 'medium',
    glycemic_index: 55,
    food_name_en: 'Chaat (Mixed)',
    food_name_ur: 'چاٹ',
    explanation_en: 'Depends on ingredients. Aloo (potato) = high GI. Chana (chickpeas) = low GI. The fried papri adds carbs. Choose chana-dominant chaat.',
    explanation_ur: 'چنے والی چاٹ بہتر ہے۔ آلو اور پاپڑی کم ڈالیں۔',
    swap_suggestion_en: 'Chana chaat with yogurt. Skip fried papri and sweet chutney.',
    swap_suggestion_ur: 'چنے اور دہی والی چاٹ کھائیں۔ میٹھی چٹنی نہ ڈالیں۔',
    portion_advice: '1 cup. Chana-heavy, papri-free.',
    carbs_g: 30,
    calories_estimate: '~180 kcal',
    category: 'snack'
  },
  {
    name: 'chana masala',
    aliases: ['chana masala', 'chickpea curry', 'chanay ka salan'],
    risk_level: 'low',
    glycemic_index: 28,
    food_name_en: 'Chana Masala',
    food_name_ur: 'چنا مصالحہ',
    explanation_en: 'Chickpeas in spiced tomato gravy. Low GI, high fiber, high protein. The tomato gravy adds lycopene. One of the best diabetic meals.',
    explanation_ur: 'چنے کا سالن شوگر کے لیے بہترین ہے۔ فائبر اور پروٹین سے بھرپور۔',
    swap_suggestion_en: 'Already optimal. Eat with 1 roti or as soup.',
    swap_suggestion_ur: 'پہلے سے بہترین ہے۔ روٹی کے ساتھ یا سوپ کی طرح کھائیں۔',
    portion_advice: '1 cup with 1 roti. Great lunch.',
    carbs_g: 30,
    calories_estimate: '~200 kcal',
    category: 'lentils'
  },
  {
    name: 'kebab roll',
    aliases: ['kebab roll', 'paratha roll', 'roll paratha', 'bun kebab roll'],
    risk_level: 'high',
    glycemic_index: 72,
    food_name_en: 'Paratha Roll / Kebab Roll',
    food_name_ur: 'پراٹھا رول',
    explanation_en: 'Fried paratha wrapped around kebab. The paratha is high GI + high fat. One roll = 55g carbs. Street food danger.',
    explanation_ur: 'پراٹھا تلا ہوا ہے، کاربوہائیڈریٹ بہت زیادہ۔',
    swap_suggestion_en: 'Whole wheat roti wrap. Or lettuce wrap with kebab.',
    swap_suggestion_ur: 'روٹی میں لپیٹ کر کھائیں۔ پراٹھا نہیں۔',
    portion_advice: 'Roti wrap version: 1 only. Avoid paratha rolls.',
    carbs_g: 55,
    calories_estimate: '~400 kcal',
    category: 'snack'
  },
  {
    name: 'chicken corn soup',
    aliases: ['chicken corn soup', 'soup', 'chicken soup', 'corn soup'],
    risk_level: 'medium',
    glycemic_index: 45,
    food_name_en: 'Chicken Corn Soup',
    food_name_ur: 'چکن کارن سوپ',
    explanation_en: 'Corn adds carbs (GI 55). The chicken broth is fine. One bowl = 25g carbs from corn. Thickener may add hidden carbs.',
    explanation_ur: 'مکئی کاربوہائیڈریٹ بڑھاتی ہے۔ چکن کا یخنی اچھا ہے۔',
    swap_suggestion_en: 'Clear chicken soup with vegetables. Skip corn and thickener.',
    swap_suggestion_ur: 'صاف چکن سوپ سبزیوں کے ساتھ۔ مکئی نہ ڈالیں۔',
    portion_advice: '1 bowl. Ask for less corn.',
    carbs_g: 25,
    calories_estimate: '~150 kcal',
    category: 'drink'
  },
  {
    name: 'seekh kebab with naan',
    aliases: ['seekh naan', 'kebab naan', 'naan seekh'],
    risk_level: 'high',
    glycemic_index: 72,
    food_name_en: 'Seekh Kebab with Naan',
    food_name_ur: 'نان کے ساتھ سیکھ کباب',
    explanation_en: 'Kebab is fine (zero carb). Naan is the problem (50g carbs). Eat the kebab, skip the naan. Use roti instead.',
    explanation_ur: 'کباب ٹھیک ہے، نان نقصان دہ ہے۔ روٹی کے ساتھ کھائیں۔',
    swap_suggestion_en: 'Seekh kebab with 1 small roti. Or kebab salad.',
    swap_suggestion_ur: 'سیکھ کباب روٹی کے ساتھ کھائیں۔ نان نہیں۔',
    portion_advice: '3-4 kebabs + 1 roti. Skip naan.',
    carbs_g: 52,
    calories_estimate: '~420 kcal',
    category: 'meat'
  },
  {
    name: 'mutton pulao',
    aliases: ['mutton pulao', 'gosht pulao', 'lamb pulao'],
    risk_level: 'high',
    glycemic_index: 65,
    food_name_en: 'Mutton Pulao',
    food_name_ur: 'مٹن پلاؤ',
    explanation_en: 'Rice with mutton. The mutton adds protein and fat which slow absorption slightly, but rice still dominates. One plate = 65g carbs.',
    explanation_ur: 'مٹن پروٹین دیتا ہے مگر چاول پھر بھی شوگر بڑھاتے ہیں۔',
    swap_suggestion_en: 'Mutton with brown rice. Or half rice, double mutton.',
    swap_suggestion_ur: 'براؤن رائس کے ساتھ کھائیں۔ چاول آدھے، گوشت زیادہ۔',
    portion_advice: '1 cup rice max. More mutton, less rice.',
    carbs_g: 65,
    calories_estimate: '~420 kcal',
    category: 'rice'
  },
  {
    name: 'hari mirch',
    aliases: ['hari mirch', 'green chili', 'mirch', 'green pepper'],
    risk_level: 'low',
    glycemic_index: 10,
    food_name_en: 'Green Chili',
    food_name_ur: 'ہری مرچ',
    explanation_en: 'Capsaicin in chilies boosts metabolism and may improve insulin sensitivity. Zero carbs. Adds flavor without calories.',
    explanation_ur: 'ہری مرچ میٹابولزم تیز کرتی ہے۔ شوگر پر اچھا اثر۔',
    swap_suggestion_en: 'Already good in moderation. Adds flavor without salt or sugar.',
    swap_suggestion_ur: 'اعتدال میں اچھی ہے۔ نمک اور چینی کے بغیر ذائقہ دیتی ہے۔',
    portion_advice: 'As tolerated. Fresh, not pickled in oil.',
    carbs_g: 1,
    calories_estimate: '~5 kcal',
    category: 'vegetables'
  },
  {
    name: 'nimbo soda',
    aliases: ['nimbo soda', 'lemon soda', 'limca', '7up', 'sprite', 'cold drink'],
    risk_level: 'high',
    glycemic_index: 74,
    food_name_en: 'Cold Drink / Soda',
    food_name_ur: 'کولڈ ڈرنک / سوڈا',
    explanation_en: 'Pure liquid sugar. One can = 35g sugar. Absorbed in minutes. ZERO nutritional value. Biggest avoidable glucose spike.',
    explanation_ur: 'کولڈ ڈرنک میں صرف چینی ہے۔ ایک کین میں 35 گرام۔ مکمل پرہیز کریں۔',
    swap_suggestion_en: 'Water with lemon and mint. Or sparkling water (soda) with lemon.',
    swap_suggestion_ur: 'لیمن پانی یا سوڈا واٹر پیئیں۔',
    portion_advice: 'NEVER.',
    carbs_g: 35,
    calories_estimate: '~140 kcal',
    category: 'drink'
  },
  {
    name: 'pakistani breakfast',
    aliases: ['nashta', 'halwa puri', 'chana puri', 'breakfast'],
    risk_level: 'high',
    glycemic_index: 80,
    food_name_en: 'Halwa Puri / Nashta',
    food_name_ur: 'حلوہ پوری / ناشتہ',
    explanation_en: 'Deep fried puri + suji halwa + chana. The puri (fried maida) and halwa (sugar + ghee) are both high risk. Chana is the only safe part.',
    explanation_ur: 'پوری تلی ہوئی، حلوہ چینی والا — دونوں نقصان دہ۔ صرف چنے کھائیں۔',
    swap_suggestion_en: 'Chana with 1 small roti + boiled egg + green tea.',
    swap_suggestion_ur: 'چنے، ایک روٹی، ابلا انڈا، اور سبز چائے۔',
    portion_advice: 'Skip puri and halwa. Eat chana + roti + egg.',
    carbs_g: 70,
    calories_estimate: '~500 kcal',
    category: 'breakfast'
  },
  {
    name: 'anda paratha',
    aliases: ['anda paratha', 'egg paratha', 'fried egg paratha'],
    risk_level: 'medium',
    glycemic_index: 65,
    food_name_en: 'Anda Paratha',
    food_name_ur: 'انڈا پراٹھا',
    explanation_en: 'Egg (zero carb) + paratha (high carb). Better than aloo paratha but still fried. One = 40g carbs + protein from egg.',
    explanation_ur: 'انڈا اچھا ہے، پراٹھا نہیں۔ روٹی پر انڈا کھائیں۔',
    swap_suggestion_en: 'Boiled eggs + 1 small roti. Or egg white omelette with roti.',
    swap_suggestion_ur: 'ابلے انڈے روٹی کے ساتھ کھائیں۔',
    portion_advice: '1 roti + 2 eggs. Skip the paratha.',
    carbs_g: 40,
    calories_estimate: '~350 kcal',
    category: 'breakfast'
  },
  {
    name: 'porridge',
    aliases: ['porridge', 'daliya', 'wheat porridge', 'sweet daliya'],
    risk_level: 'medium',
    glycemic_index: 55,
    food_name_en: 'Daliya (Porridge)',
    food_name_ur: 'دلیہ',
    explanation_en: 'Broken wheat porridge. Moderate GI. High fiber if unsweetened. Sweet daliya (with sugar) = high risk. Savory daliya is better.',
    explanation_ur: 'بغیر چینی کا دلیہ اچھا ہے۔ میٹھا دلیہ نقصان دہ۔',
    swap_suggestion_en: 'Savory daliya with vegetables. Or oats with cinnamon.',
    swap_suggestion_ur: 'نمکین دلیہ سبزیوں کے ساتھ کھائیں۔',
    portion_advice: '1 cup cooked. Without sugar.',
    carbs_g: 25,
    calories_estimate: '~120 kcal',
    category: 'breakfast'
  },
  {
    name: 'qatlam',
    aliases: ['qatlam', 'katlam', 'fried bread', 'qatlama'],
    risk_level: 'high',
    glycemic_index: 80,
    food_name_en: 'Qatlam (Fried Bread)',
    food_name_ur: 'قلمہ',
    explanation_en: 'Deep fried layered bread. Very high fat + high carb. Popular in KPK and Punjab. Extremely unhealthy for diabetics.',
    explanation_ur: 'تلی ہوئی روٹی شوگر اور کولیسٹرول دونوں بڑھاتی ہے۔',
    swap_suggestion_en: 'Tandoori roti or whole wheat chapati.',
    swap_suggestion_ur: 'تندوری روٹی یا گندم کی چپاتی کھائیں۔',
    portion_advice: 'ZERO. Replace with roti.',
    carbs_g: 45,
    calories_estimate: '~380 kcal',
    category: 'bread'
  },
  {
    name: 'roghni naan',
    aliases: ['roghni naan', 'oil naan', 'butter naan'],
    risk_level: 'high',
    glycemic_index: 78,
    food_name_en: 'Roghni Naan',
    food_name_ur: 'روغنی نان',
    explanation_en: 'Maida + oil/ghee + yogurt. High GI, high fat, high calorie. One naan = 55g carbs + 15g fat. Very bad for diabetics.',
    explanation_ur: 'روغنی نان میدے اور گھی سے بنا — بہت نقصان دہ۔',
    swap_suggestion_en: '1 small tandoori roti. Or multigrain roti.',
    swap_suggestion_ur: 'چھوٹی تندوری روٹی کھائیں۔',
    portion_advice: 'ZERO. Use roti always.',
    carbs_g: 55,
    calories_estimate: '~400 kcal',
    category: 'bread'
  },
  {
    name: 'sevaiyan',
    aliases: ['sevaiyan', 'vermicelli', 'meethi sevaiyan', 'eid sevaiyan'],
    risk_level: 'high',
    glycemic_index: 75,
    food_name_en: 'Sevaiyan (Vermicelli)',
    food_name_ur: 'سویاں',
    explanation_en: 'Vermicelli + milk + sugar + dry fruits. Eid breakfast staple. Very high carb + sugar. One bowl = 60g carbs.',
    explanation_ur: 'سویوں میں چینی، دودھ، اور میدہ — تینوں نقصان دہ۔',
    swap_suggestion_en: 'Sugar-free sevaiyan with stevia. Half portion with extra nuts.',
    swap_suggestion_ur: 'سٹیویا سے سویاں بنائیں۔ آدھی پیالی۔',
    portion_advice: 'ZERO. Sugar-free: half cup.',
    carbs_g: 60,
    calories_estimate: '~300 kcal',
    category: 'dessert'
  },
  {
    name: 'gajar halwa',
    aliases: ['gajar halwa', 'carrot halwa', 'gajar ka halwa'],
    risk_level: 'medium',
    glycemic_index: 55,
    food_name_en: 'Gajar Halwa',
    food_name_ur: 'گاجر کا حلوہ',
    explanation_en: 'Carrots + milk + sugar. Carrots have moderate GI. The khoya and sugar make it high calorie. Better than suji halwa but still dangerous.',
    explanation_ur: 'گاجر اچھی ہے مگر چینی اور کھویا نقصان دہ ہیں۔',
    swap_suggestion_en: 'Grated carrots with nuts, no sugar. Stevia-sweetened version.',
    swap_suggestion_ur: 'کدوکش گاجر بادام کے ساتھ، بغیر چینی۔',
    portion_advice: 'Half cup if sugar-free. Avoid regular.',
    carbs_g: 30,
    calories_estimate: '~200 kcal',
    category: 'dessert'
  },
  {
    name: 'pomegranate',
    aliases: ['pomegranate', 'anar', 'pomegrenate', 'anaar'],
    risk_level: 'low',
    glycemic_index: 18,
    food_name_en: 'Pomegranate (Anar)',
    food_name_ur: 'انار',
    explanation_en: 'Very low GI. Rich in antioxidants that protect pancreatic beta cells. The seeds provide fiber. Excellent diabetic fruit.',
    explanation_ur: 'انار شوگر کے لیے بہترین پھل ہے۔ انسولین کو بہتر کرتا ہے۔',
    swap_suggestion_en: 'Already optimal. Eat fresh, not juiced (juice removes fiber).',
    swap_suggestion_ur: 'پہلے سے بہترین ہے۔ جوس نہیں، پورا پھل کھائیں۔',
    portion_advice: '1 small anar daily. Or half cup seeds.',
    carbs_g: 14,
    calories_estimate: '~60 kcal',
    category: 'fruit'
  },
  {
    name: 'guava',
    aliases: ['guava', 'amrood', 'amrud', 'jam'],
    risk_level: 'low',
    glycemic_index: 12,
    food_name_en: 'Guava (Amrood)',
    food_name_ur: 'امرود',
    explanation_en: 'Extremely low GI (12). Highest vitamin C among fruits. Very high fiber. The best fruit for diabetics in Pakistan.',
    explanation_ur: 'امرود سب سے کم GI والا پھل ہے۔ شوگر مریضوں کے لیے بہترین۔',
    swap_suggestion_en: 'Already optimal. Eat with peel for maximum fiber.',
    swap_suggestion_ur: 'پہلے سے بہترین ہے۔ چھلکے سمیت کھائیں۔',
    portion_advice: '1-2 daily. Best diabetic fruit.',
    carbs_g: 8,
    calories_estimate: '~35 kcal',
    category: 'fruit'
  },
  {
    name: 'apple',
    aliases: ['apple', 'seb', 'saib'],
    risk_level: 'low',
    glycemic_index: 36,
    food_name_en: 'Apple (Seb)',
    food_name_ur: 'سیب',
    explanation_en: 'Low GI. Pectin fiber slows sugar absorption. Eat with peel. One small apple = 15g carbs. Good snack for diabetics.',
    explanation_ur: 'سیب کا چھلکا فائبر دیتا ہے۔ ایک چھوٹا سیب اچھا سنیک ہے۔',
    swap_suggestion_en: 'Already good. Eat with peel and pair with nuts.',
    swap_suggestion_ur: 'پہلے سے اچھا ہے۔ چھلکے سمیت، بادام کے ساتھ کھائیں۔',
    portion_advice: '1 small apple daily. Best with nuts.',
    carbs_g: 15,
    calories_estimate: '~60 kcal',
    category: 'fruit'
  },
  {
    name: 'banana',
    aliases: ['banana', 'kela', 'keela'],
    risk_level: 'medium',
    glycemic_index: 51,
    food_name_en: 'Banana (Kela)',
    food_name_ur: 'کیلا',
    explanation_en: 'Medium GI. Riper = higher GI. One medium banana = 27g carbs. Good for quick energy, not ideal for diabetics.',
    explanation_ur: 'کیلا درمیانہ خطرہ۔ زیادہ پکا کیلا شوگر زیادہ بڑھاتا ہے۔',
    swap_suggestion_en: 'Half green banana. Or switch to apple/guava.',
    swap_suggestion_ur: 'آدھا کچا کیلا کھائیں۔ یا سیب/امرود کھائیں۔',
    portion_advice: 'Half banana. Not daily.',
    carbs_g: 27,
    calories_estimate: '~105 kcal',
    category: 'fruit'
  },
  {
    name: 'watermelon',
    aliases: ['watermelon', 'tarbooz', 'tarbuz', 'water melon'],
    risk_level: 'medium',
    glycemic_index: 72,
    food_name_en: 'Watermelon (Tarbooz)',
    food_name_ur: 'تربوز',
    explanation_en: 'High GI (72) despite being mostly water. The sugar absorbs very fast. 1 cup = 12g carbs. Summer favorite but watch portions.',
    explanation_ur: 'تربوز کا GI زیادہ ہے۔ تھوڑی مقدار میں کھائیں۔',
    swap_suggestion_en: 'Limit to 1 small slice. Pair with feta cheese or nuts.',
    swap_suggestion_ur: 'ایک چھوٹا ٹکڑا کافی ہے۔ پنیر یا بادام کے ساتھ کھائیں۔',
    portion_advice: '1 small slice. Not a whole plate.',
    carbs_g: 12,
    calories_estimate: '~45 kcal',
    category: 'fruit'
  },
  {
    name: 'papaya',
    aliases: ['papaya', 'papita', 'papeeta'],
    risk_level: 'low',
    glycemic_index: 38,
    food_name_en: 'Papaya (Papita)',
    food_name_ur: 'پپیتا',
    explanation_en: 'Low GI. Rich in papain enzyme which aids digestion. Good fiber content. Excellent fruit for diabetics.',
    explanation_ur: 'پپیتا شوگر کے لیے اچھا ہے۔ ہاضمے میں مدد دیتا ہے۔',
    swap_suggestion_en: 'Already good. Eat fresh, not canned in syrup.',
    swap_suggestion_ur: 'پہلے سے اچھا ہے۔ تازہ کھائیں، ڈبہ بند نہیں۔',
    portion_advice: '1 cup. Daily is fine.',
    carbs_g: 11,
    calories_estimate: '~45 kcal',
    category: 'fruit'
  },
  {
    name: 'grapes',
    aliases: ['grapes', 'angoor', 'angur'],
    risk_level: 'medium',
    glycemic_index: 53,
    food_name_en: 'Grapes (Angoor)',
    food_name_ur: 'انگور',
    explanation_en: 'Medium GI. Very easy to overeat (who stops at 10 grapes?). 1 cup = 27g sugar. Portion control is key.',
    explanation_ur: 'انگور کم مقدار میں کھائیں۔ ایک کپ میں 27 گرام چینی ہے۔',
    swap_suggestion_en: 'Count to 15 grapes max. Pair with cheese.',
    swap_suggestion_ur: '15 دانے سے زیادہ نہ کھائیں۔ پنیر کے ساتھ کھائیں۔',
    portion_advice: '15 grapes max. Not the whole bunch.',
    carbs_g: 27,
    calories_estimate: '~100 kcal',
    category: 'fruit'
  },
  {
    name: 'coconut',
    aliases: ['coconut', 'nariyal', 'khopra', 'coconut water'],
    risk_level: 'medium',
    glycemic_index: 45,
    food_name_en: 'Coconut',
    food_name_ur: 'ناریل',
    explanation_en: 'Coconut flesh is high fat, low carb. Coconut water has natural sugar (6g/cup). Flesh is fine, water in moderation.',
    explanation_ur: 'ناریل کا پانی اعتدال میں پیئیں۔ گودا ٹھیک ہے۔',
    swap_suggestion_en: 'Fresh coconut flesh is fine. Limit coconut water to 1 cup.',
    swap_suggestion_ur: 'تازہ ناریل کا گودا کھائیں۔ پانی ایک کپ سے زیادہ نہ پیئیں۔',
    portion_advice: '1 cup coconut water max. Fresh flesh: 2 tbsp.',
    carbs_g: 6,
    calories_estimate: '~50 kcal',
    category: 'fruit'
  },
  {
    name: 'almonds',
    aliases: ['almonds', 'badam', 'kaju badam'],
    risk_level: 'low',
    glycemic_index: 0,
    food_name_en: 'Almonds (Badam)',
    food_name_ur: 'بادام',
    explanation_en: 'Zero GI. Rich in magnesium, vitamin E, healthy fats. 10 almonds = 3g carbs. Eat before meals to reduce glucose spike by 30%.',
    explanation_ur: 'بادام شوگر نہیں بڑھاتے۔ کھانے سے پہلے 10 بادام کھائیں۔',
    swap_suggestion_en: 'Already optimal. Soaked overnight for better absorption.',
    swap_suggestion_ur: 'پہلے سے بہترین ہے۔ رات کو بھگو کر صبح کھائیں۔',
    portion_advice: '10-15 daily. Before meals.',
    carbs_g: 3,
    calories_estimate: '~80 kcal',
    category: 'herbs'
  },
  {
    name: 'walnuts',
    aliases: ['walnuts', 'akhrot', 'akhroat'],
    risk_level: 'low',
    glycemic_index: 0,
    food_name_en: 'Walnuts (Akhrot)',
    food_name_ur: 'اخروٹ',
    explanation_en: 'Rich in omega-3 and alpha-lipoic acid. Zero GI. Reduces inflammation and improves insulin sensitivity. Brain-shaped nut for brain health.',
    explanation_ur: 'اخروٹ میں اومیگا-3 ہے۔ شوگر کم کرنے میں مدد دیتا ہے۔',
    swap_suggestion_en: 'Already optimal. 5 halves daily.',
    swap_suggestion_ur: 'پہلے سے بہترین ہے۔ روزانہ 5 آدھے اخروٹ کھائیں۔',
    portion_advice: '5 walnut halves daily.',
    carbs_g: 2,
    calories_estimate: '~65 kcal',
    category: 'herbs'
  },
  {
    name: 'peanuts',
    aliases: ['peanuts', 'moongphali', 'mumphali', 'groundnuts'],
    risk_level: 'low',
    glycemic_index: 14,
    food_name_en: 'Peanuts (Moongphali)',
    food_name_ur: 'مونگ پھلی',
    explanation_en: 'Legume with very low GI. High protein + healthy fat. Roasted is better than fried. Excellent diabetic snack.',
    explanation_ur: 'مونگ پھلی شوگر نہیں بڑھاتی۔ بھنی ہوئی کھائیں، تلی ہوئی نہیں۔',
    swap_suggestion_en: 'Already good. Dry roasted, unsalted. Avoid fried/salted.',
    swap_suggestion_ur: 'پہلے سے اچھی ہے۔ بھنی ہوئی، بغیر نمک۔',
    portion_advice: '1 handful (30g). Good snack.',
    carbs_g: 5,
    calories_estimate: '~160 kcal',
    category: 'herbs'
  },
  {
    name: 'dar chini',
    aliases: ['dar chini', 'cinnamon', 'dalchini', 'cinnamon tea'],
    risk_level: 'low',
    glycemic_index: 0,
    food_name_en: 'Cinnamon (Dar Chini)',
    food_name_ur: 'دار چینی',
    explanation_en: 'Proven to reduce fasting glucose by 18-29%. Mimics insulin. 1 tsp daily in tea or food. Ceylon cinnamon is safer than Cassia.',
    explanation_ur: 'دار چینی شوگر 18-29% کم کرتی ہے۔ روزانہ چائے یا کھانے میں ڈالیں۔',
    swap_suggestion_en: 'Already optimal. Ceylon cinnamon preferred for daily use.',
    swap_suggestion_ur: 'پہلے سے بہترین ہے۔ روزانہ استعمال کریں۔',
    portion_advice: '1 tsp daily. In tea, oats, or dal.',
    carbs_g: 0,
    calories_estimate: '~3 kcal',
    category: 'herbs'
  },
  {
    name: 'haldi',
    aliases: ['haldi', 'turmeric', 'haldi doodh', 'turmeric milk'],
    risk_level: 'low',
    glycemic_index: 0,
    food_name_en: 'Turmeric (Haldi)',
    food_name_ur: 'ہلدی',
    explanation_en: 'Curcumin reduces inflammation and improves insulin sensitivity. 1 tsp daily in food or milk. Black pepper increases absorption by 2000%.',
    explanation_ur: 'ہلدی سوزش کم کرتی ہے۔ کالی مرچ کے ساتھ لیں تاکہ زیادہ اثر ہو۔',
    swap_suggestion_en: 'Already optimal. Always pair with black pepper.',
    swap_suggestion_ur: 'پہلے سے بہترین ہے۔ کالی مرچ کے ساتھ استعمال کریں۔',
    portion_advice: '1 tsp daily in cooking.',
    carbs_g: 1,
    calories_estimate: '~8 kcal',
    category: 'herbs'
  },
  {
    name: 'adrak',
    aliases: ['adrak', 'ginger', 'adrak chai', 'ginger tea'],
    risk_level: 'low',
    glycemic_index: 0,
    food_name_en: 'Ginger (Adrak)',
    food_name_ur: 'ادرک',
    explanation_en: 'Gingerol reduces fasting glucose and HbA1c. Add to tea or food daily. 2g fresh ginger = significant benefits.',
    explanation_ur: 'ادرک شوگر اور HbA1c کم کرتی ہے۔ روزانہ چائے میں ڈالیں۔',
    swap_suggestion_en: 'Already optimal. Fresh ginger > powder.',
    swap_suggestion_ur: 'پہلے سے بہترین ہے۔ تازہ ادرک بہتر ہے۔',
    portion_advice: '2g fresh daily. In tea or food.',
    carbs_g: 0,
    calories_estimate: '~2 kcal',
    category: 'herbs'
  },
  {
    name: 'lehsun',
    aliases: ['lehsun', 'garlic', 'garlic clove', 'lasan'],
    risk_level: 'low',
    glycemic_index: 0,
    food_name_en: 'Garlic (Lehsun)',
    food_name_ur: 'لہسن',
    explanation_en: 'Allicin in garlic reduces fasting glucose and improves heart health. 1-2 cloves daily raw or cooked. Must be crushed 10 min before cooking.',
    explanation_ur: 'لہسن شوگر کم کرتا ہے اور دل کے لیے اچھا ہے۔ روزانہ 1-2 جو کھائیں۔',
    swap_suggestion_en: 'Already optimal. Crush and let sit 10 min before cooking.',
    swap_suggestion_ur: 'پہلے سے بہترین ہے۔ کچل کر 10 منٹ بعد پکائیں۔',
    portion_advice: '1-2 cloves daily.',
    carbs_g: 1,
    calories_estimate: '~4 kcal',
    category: 'herbs'
  },
  {
    name: 'piaz',
    aliases: ['piaz', 'onion', 'raw onion', 'pyaz'],
    risk_level: 'low',
    glycemic_index: 10,
    food_name_en: 'Onion (Piaz)',
    food_name_ur: 'پیاز',
    explanation_en: 'Quercetin in onions helps regulate blood sugar. Raw onion is better than cooked. Eat with meals (kachoomar/salad).',
    explanation_ur: 'کچی پیاز شوگر کنٹرول کرتی ہے۔ کھانے کے ساتھ سلاد میں کھائیں۔',
    swap_suggestion_en: 'Already optimal. Raw is better than fried.',
    swap_suggestion_ur: 'پہلے سے بہترین ہے۔ کچی پیاز زیادہ فائدہ مند ہے۔',
    portion_advice: 'Quarter onion with every meal. Raw preferred.',
    carbs_g: 8,
    calories_estimate: '~30 kcal',
    category: 'vegetables'
  },
  {
    name: 'tamatar',
    aliases: ['tamatar', 'tomato', 'tamatar salan'],
    risk_level: 'low',
    glycemic_index: 15,
    food_name_en: 'Tomato (Tamatar)',
    food_name_ur: 'ٹماٹر',
    explanation_en: 'Lycopene-rich, low GI. Reduces oxidative stress. Cooked tomatoes release more lycopene. Excellent in salan or raw.',
    explanation_ur: 'ٹماٹر شوگر کم کرنے میں مدد دیتا ہے۔ پکا کر یا کچا کھائیں۔',
    swap_suggestion_en: 'Already optimal. Cooked for lycopene, raw for vitamin C.',
    swap_suggestion_ur: 'پہلے سے بہترین ہے۔',
    portion_advice: '2 medium tomatoes daily. Unlimited.',
    carbs_g: 5,
    calories_estimate: '~25 kcal',
    category: 'vegetables'
  },
  {
    name: 'shaljam',
    aliases: ['shaljam', 'turnip', 'shaljam sabzi'],
    risk_level: 'low',
    glycemic_index: 30,
    food_name_en: 'Turnip (Shaljam)',
    food_name_ur: 'شلجم',
    explanation_en: 'Low GI root vegetable. Good potato replacement. One cup = 8g carbs (vs 30g for potato). Great in salan or roasted.',
    explanation_ur: 'شلجم آلو کا اچھا متبادل ہے۔ کاربوہائیڈریٹ بہت کم ہے۔',
    swap_suggestion_en: 'Replace potato with turnip in all salans.',
    swap_suggestion_ur: 'آلو کی جگہ شلجم ڈالیں۔',
    portion_advice: 'Unlimited. Great potato alternative.',
    carbs_g: 8,
    calories_estimate: '~35 kcal',
    category: 'vegetables'
  },
  {
    name: 'tinde',
    aliases: ['tinde', 'tinda', 'round gourd', 'tinda sabzi'],
    risk_level: 'low',
    glycemic_index: 20,
    food_name_en: 'Tinda (Round Gourd)',
    food_name_ur: 'ٹنڈے',
    explanation_en: 'Very low GI gourd. High water content. Light and easy to digest. Good for diabetics wanting variety from karela.',
    explanation_ur: 'ٹنڈے شوگر نہیں بڑھاتے۔ ہلکے اور ہاضمے کے لیے اچھے۔',
    swap_suggestion_en: 'Already optimal. Cook with minimal oil.',
    swap_suggestion_ur: 'پہلے سے بہترین ہے۔ کم تیل میں پکائیں۔',
    portion_advice: '1 cup. Daily if desired.',
    carbs_g: 4,
    calories_estimate: '~20 kcal',
    category: 'vegetables'
  },
  {
    name: 'cake',
    aliases: ['cake', 'birthday cake', 'cupcake', 'bakery', 'pastry', 'kek', 'کیک',
              'chocolate cake', 'cream cake', 'wedding cake', 'swiss roll', 'muffin',
              'brownie', 'black forest', 'vanilla cake', 'fruit cake'],
    risk_level: 'high',
    glycemic_index: 82,
    food_name_en: 'Cake / Pastry',
    food_name_ur: 'کیک / پیسٹری',
    explanation_en: 'Refined flour + sugar + butter. One slice = 50-60g carbs + 30g sugar. Rapid glucose spike within 15-20 minutes. Extremely high glycemic load.',
    explanation_ur: 'کیک میں 50+ گرام چینی ہے — شوگر کے مریضوں کے لیے نقصاندہ۔ ایک ٹکڑے میں 30 گرام چینی، 15-20 منٹ میں شوگر بڑھ جاتی ہے۔',
    swap_suggestion_en: '1-2 dates or fresh fruit salad. If unavoidable at celebrations, 1 small bite only.',
    swap_suggestion_ur: '1-2 کھجور یا پھل بہتر ہے۔ مجبوری ہو تو ایک چھوٹا ٹکڑا کافی ہے۔',
    portion_advice: 'ZERO for diabetics. 1 small bite maximum if unavoidable at celebrations.',
    carbs_g: 52,
    calories_estimate: '~350 kcal',
    category: 'dessert'
  }
];

// ==================== SEARCH ENGINE ====================

class OfflineDatabase {
  constructor() {
    this.foods = PAKISTANI_FOODS;
    this.initialized = true;
    console.log(`✅ SehatGemma Offline DB ready: ${this.foods.length} Pakistani foods`);
  }

  /**
   * Search for a food by text query
   * Returns structured result matching the same format as backend /analyze endpoint
   */
  searchFood(query) {
    if (!query || !query.trim()) {
      return this._unknownResult(query);
    }

    const cleanQuery = query.toLowerCase().trim();
    const words = cleanQuery.split(/\s+/);

    // Tier 1: Exact name match
    let match = this.foods.find(f => f.name === cleanQuery);
    if (match) return this._formatResult(match, 'exact');

    // Tier 2: Exact alias match
    match = this.foods.find(f => f.aliases.some(a => a === cleanQuery));
    if (match) return this._formatResult(match, 'exact');

    // Tier 3: Name contains query
    match = this.foods.find(f => f.name.includes(cleanQuery));
    if (match) return this._formatResult(match, 'partial');

    // Tier 4: Any alias contains query
    match = this.foods.find(f => f.aliases.some(a => a.includes(cleanQuery)));
    if (match) return this._formatResult(match, 'partial');

    // Tier 5: Query contains food name
    match = this.foods.find(f => cleanQuery.includes(f.name));
    if (match) return this._formatResult(match, 'partial');

    // Tier 6: Word-by-word matching (at least one word matches)
    for (const word of words) {
      if (word.length < 3) continue; // Skip short words
      match = this.foods.find(f =>
        f.name.includes(word) || f.aliases.some(a => a.includes(word))
      );
      if (match) return this._formatResult(match, 'partial');
    }

    // Tier 7: Category match
    match = this.foods.find(f => f.category === cleanQuery);
    if (match) return this._formatResult(match, 'partial');

    // No match found
    return this._unknownResult(query);
  }

  /**
   * Get all foods in a category
   */
  getByCategory(category) {
    return this.foods
      .filter(f => f.category === category.toLowerCase())
      .map(f => this._formatResult(f, 'exact'));
  }

  /**
   * Get all safe (low risk) foods
   */
  getSafeFoods() {
    return this.foods
      .filter(f => f.risk_level === 'low')
      .map(f => this._formatResult(f, 'exact'));
  }

  /**
   * Get all categories
   */
  getCategories() {
    const cats = [...new Set(this.foods.map(f => f.category))];
    return cats.sort();
  }

  /**
   * Format a matched food into the standard result structure
   */
  _formatResult(food, matchType) {
    const riskColors = {
      low: '#2E7D32',
      medium: '#F57F17',
      high: '#ba1a1a'
    };

    return {
      // Standard fields matching backend response
      food_name_en: food.food_name_en,
      food_name_ur: food.food_name_ur,
      sugar_risk: food.risk_level,
      explanation_en: food.explanation_en,
      explanation_ur: food.explanation_ur,
      swap_suggestion_en: food.swap_suggestion_en,
      swap_suggestion_ur: food.swap_suggestion_ur,
      confidence: matchType === 'exact' ? 95 : 75,
      carbs_g: food.carbs_g,
      calories_estimate: food.calories_estimate,
      key_ingredients: [],
      agent_action: 'analyze_meal',

      // Offline-specific metadata
      offline: true,
      match_type: matchType,
      glycemic_index: food.glycemic_index,
      portion_advice: food.portion_advice,
      category: food.category,
      risk_color: riskColors[food.risk_level] || '#6b7280',
      disclaimer: 'یہ مقامی ڈیٹا بیس کا تجزیہ ہے۔ بڑی تبدیلیوں سے پہلے ڈاکٹر سے مشورہ کریں۔'
    };
  }

  /**
   * Format unknown food result
   */
  _unknownResult(query) {
    return {
      food_name_en: query || 'Unknown Food',
      food_name_ur: 'نامعلوم کھانا',
      sugar_risk: 'unknown',
      explanation_en: `"${query || 'This food'}" was not found in our offline Pakistani food database. It may be a non-Pakistani or uncommon food. Connect to SehatGemma backend for AI-powered analysis.`,
      explanation_ur: `"${query || 'یہ کھانا'}" ہمارے مقامی ڈیٹا بیس میں نہیں ملا۔ بیک اینڈ سے منسلک ہوں تاکہ AI تجزیہ حاصل کرسکیں۔`,
      swap_suggestion_en: 'For unknown foods, keep portions small and check blood sugar after 2 hours.',
      swap_suggestion_ur: 'نامعلوم کھانوں کے لیے، تھوڑی مقدار کھائیں اور 2 گھنٹے بعد شوگر چیک کریں۔',
      confidence: 0,
      carbs_g: 0,
      calories_estimate: 'N/A',
      key_ingredients: [],
      agent_action: 'analyze_meal',
      offline: true,
      match_type: 'unknown',
      glycemic_index: null,
      portion_advice: 'Start with half cup and check blood sugar after 2 hours.',
      category: 'unknown',
      risk_color: '#6b7280',
      disclaimer: 'براہ کرم انٹرنیٹ سے منسلک ہوں تاکہ AI تجزیہ حاصل کرسکیں، یا ڈاکٹر سے مشورہ کریں۔'
    };
  }
}

// Singleton instance
export const offlineDB = new OfflineDatabase();
export { PAKISTANI_FOODS };